// Demo deal for development and demonstration
const DEMO_DEAL = {
  id: '00000000-0000-0000-0000-000000000001',
  slug: 'fairmont-apartments',
  name: 'Fairmont Apartments',
  status: 'live',
  property_address: '4985 Warner Rd, Westerville, OH 43081',
  city: 'Westerville',
  state: 'OH',
  total_units: 219,
  total_raise: 22_100_000,
  min_investment: 100_000,
  purchase_price: 62_500_000,
  projected_hold_years: 7,
  target_irr_base: 0.15,          // midpoint of 14-16% target
  target_irr_conservative: 0.10,
  target_equity_multiple: 2.2,
  target_coc: 0.084,              // avg cash-on-cash over hold
  hero_image_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1920&q=80',
  hero_video_url: '',
  video_url: '',
  market_analysis_md: `Columbus is the 14th largest MSA in the United States with a population of over 2.1 million and one of the fastest-growing metros in the Midwest. The metro is anchored by The Ohio State University, major healthcare systems (OhioHealth, Nationwide Children's Hospital), technology (AWS, Google, Intel), and financial services (JPMorgan Chase, Nationwide Insurance).

The Westerville submarket, where Fairmont Apartments is located, benefits from top-rated schools, proximity to major employment corridors, and structurally limited new multifamily supply. Current submarket vacancy is approximately 4.0%, well below the national average.

Rent growth in the Columbus MSA has been strong and consistent. Intel's $20B semiconductor campus in New Albany (4 miles away) and Anduril's defense manufacturing hub represent significant long-term demand catalysts. New supply in Westerville is structurally constrained by land and zoning, creating a durable competitive moat for Fairmont Apartments.`,
  business_plan_md: `Fairmont Apartments is a brand new Class A multifamily community in Westerville, OH — one of Columbus' most supply-constrained and high-demand suburbs. The property benefits from a 15-year tax abatement that significantly reduces operating costs and enhances investor returns during the hold period.

Our strategy: acquire a high-quality, newly constructed asset at $285K/unit, below estimated replacement cost of $350K+, and capture organic rent growth in a supply-constrained submarket with major demand catalysts (Intel, Anduril, OSU). Gray Residential manages the property from day one, implementing our proven revenue management, retention, and operational efficiency systems.

The 15-year tax abatement is a significant differentiator — it substantially reduces property tax expense, boosting NOI and investor distributions. Combined with Class A quality and Westerville's structural supply constraints, Fairmont Apartments is positioned for consistent, low-execution-risk returns.`,
  team_override_md: null,
  fundraise_pct: null,
  sensitivity_data: {
    deal_slug: 'fairmont-apartments',
    scenarios: {
      downside: {
        label: 'Conservative',
        assumptions: {
          annual_rent_growth: 0.03,
          exit_cap: 0.0600,
          avg_occupancy: 0.92,
          annual_expense_growth: 0.035,
        },
        returns: {
          lp_irr: 0.105,          // ~10-11%
          equity_multiple: 1.8,
          avg_coc: 0.07,
          distribution_per_100k: 180_000,
        },
      },
      base: {
        label: 'Base Case',
        assumptions: {
          annual_rent_growth: 0.04,
          exit_cap: 0.0550,
          avg_occupancy: 0.935,
          annual_expense_growth: 0.03,
        },
        returns: {
          lp_irr: 0.15,           // 14-16% base case
          equity_multiple: 2.2,
          avg_coc: 0.084,
          distribution_per_100k: 220_000,
        },
      },
      upside: {
        label: 'Upside',
        assumptions: {
          annual_rent_growth: 0.05,
          exit_cap: 0.0525,
          avg_occupancy: 0.95,
          annual_expense_growth: 0.025,
        },
        returns: {
          lp_irr: 0.175,          // ~17-18%
          equity_multiple: 2.5,
          avg_coc: 0.095,
          distribution_per_100k: 250_000,
        },
      },
      strategic: {
        label: 'Strategic',
        description: 'Intel + Anduril demand catalysts fully realized',
        assumptions: {
          annual_rent_growth: 0.06,
          exit_cap: 0.0500,
          avg_occupancy: 0.96,
          annual_expense_growth: 0.025,
        },
        returns: {
          lp_irr: 0.21,           // 20%+
          equity_multiple: 2.8,
          avg_coc: 0.105,
          distribution_per_100k: 280_000,
        },
      },
    },
    sensitivity_tables: {
      rent_growth_vs_irr: [
        { rent_growth: 0.000, irr: 0.082, equity_multiple: 1.45, avg_coc: 0.051 },
        { rent_growth: 0.005, irr: 0.091, equity_multiple: 1.52, avg_coc: 0.055 },
        { rent_growth: 0.010, irr: 0.101, equity_multiple: 1.59, avg_coc: 0.058 },
        { rent_growth: 0.015, irr: 0.110, equity_multiple: 1.66, avg_coc: 0.062 },
        { rent_growth: 0.020, irr: 0.120, equity_multiple: 1.73, avg_coc: 0.065 },
        { rent_growth: 0.025, irr: 0.130, equity_multiple: 1.80, avg_coc: 0.068 },
        { rent_growth: 0.030, irr: 0.142, equity_multiple: 1.88, avg_coc: 0.070 },
        { rent_growth: 0.035, irr: 0.158, equity_multiple: 1.95, avg_coc: 0.072 },
        { rent_growth: 0.040, irr: 0.172, equity_multiple: 2.05, avg_coc: 0.075 },
        { rent_growth: 0.045, irr: 0.188, equity_multiple: 2.16, avg_coc: 0.078 },
        { rent_growth: 0.050, irr: 0.205, equity_multiple: 2.28, avg_coc: 0.081 },
      ],
      exit_cap_vs_irr: [
        { exit_cap: 0.040, irr: 0.225, equity_multiple: 2.50 },
        { exit_cap: 0.043, irr: 0.205, equity_multiple: 2.32 },
        { exit_cap: 0.045, irr: 0.192, equity_multiple: 2.20 },
        { exit_cap: 0.048, irr: 0.175, equity_multiple: 2.08 },
        { exit_cap: 0.050, irr: 0.165, equity_multiple: 2.00 },
        { exit_cap: 0.053, irr: 0.158, equity_multiple: 1.95 },
        { exit_cap: 0.055, irr: 0.145, equity_multiple: 1.85 },
        { exit_cap: 0.058, irr: 0.130, equity_multiple: 1.75 },
        { exit_cap: 0.060, irr: 0.118, equity_multiple: 1.68 },
        { exit_cap: 0.065, irr: 0.095, equity_multiple: 1.52 },
        { exit_cap: 0.070, irr: 0.072, equity_multiple: 1.38 },
      ],
      occupancy_vs_irr: [
        { occupancy: 0.85, irr: 0.065, equity_multiple: 1.32 },
        { occupancy: 0.87, irr: 0.082, equity_multiple: 1.42 },
        { occupancy: 0.89, irr: 0.100, equity_multiple: 1.55 },
        { occupancy: 0.91, irr: 0.120, equity_multiple: 1.68 },
        { occupancy: 0.93, irr: 0.142, equity_multiple: 1.82 },
        { occupancy: 0.94, irr: 0.158, equity_multiple: 1.95 },
        { occupancy: 0.95, irr: 0.168, equity_multiple: 2.02 },
        { occupancy: 0.96, irr: 0.180, equity_multiple: 2.12 },
        { occupancy: 0.97, irr: 0.195, equity_multiple: 2.22 },
        { occupancy: 0.98, irr: 0.210, equity_multiple: 2.32 },
      ],
      rent_growth_x_exit_cap: [
        { rent_growth: 0.020, exit_cap: 0.045, irr: 0.155 },
        { rent_growth: 0.020, exit_cap: 0.050, irr: 0.135 },
        { rent_growth: 0.020, exit_cap: 0.055, irr: 0.115 },
        { rent_growth: 0.020, exit_cap: 0.060, irr: 0.095 },
        { rent_growth: 0.035, exit_cap: 0.045, irr: 0.195 },
        { rent_growth: 0.035, exit_cap: 0.050, irr: 0.172 },
        { rent_growth: 0.035, exit_cap: 0.053, irr: 0.158 },
        { rent_growth: 0.035, exit_cap: 0.060, irr: 0.128 },
        { rent_growth: 0.045, exit_cap: 0.045, irr: 0.228 },
        { rent_growth: 0.045, exit_cap: 0.048, irr: 0.210 },
        { rent_growth: 0.045, exit_cap: 0.053, irr: 0.185 },
        { rent_growth: 0.045, exit_cap: 0.060, irr: 0.152 },
      ],
    },
    annual_cash_flows: {
      // 7-year projections (exact deck numbers)
      base: [
        { year: 1, egr: 5_100_000, noi: 3_000_000, tax_abatement: 895_000,  coc: 0.0753 },
        { year: 2, egr: 5_400_000, noi: 3_200_000, tax_abatement: 922_000,  coc: 0.0847 },
        { year: 3, egr: 5_600_000, noi: 3_300_000, tax_abatement: 950_000,  coc: 0.0800 },
        { year: 4, egr: 5_800_000, noi: 3_500_000, tax_abatement: 978_000,  coc: 0.0920 },
        { year: 5, egr: 6_000_000, noi: 3_600_000, tax_abatement: 1_000_000, coc: 0.0790 },
        { year: 6, egr: 6_200_000, noi: 3_800_000, tax_abatement: 1_000_000, coc: 0.0825 },
        { year: 7, egr: 6_500_000, noi: 4_000_000, tax_abatement: 1_100_000, coc: 0.0916 },
      ],
    },
    waterfall: {
      pref_rate: 0.08,
      pref_type: 'cumulative_non_compounding',
      pref_basis: 'committed_capital',
      lp_split: 0.80,
      gp_split: 0.20,
      catch_up: false,
    },
    deal_terms: {
      total_raise: 22_100_000,
      min_investment: 100_000,
      projected_hold_years: 7,
      purchase_price: 62_500_000,
      total_capitalization: 65_832_000,
      total_units: 219,
      loan_amount: 43_750_000,
      interest_rate: 0.0517,
      ltv: 0.70,
      io_months: 48,
    },
    cost_seg: {
      year_1_accelerated_depreciation_pct: 0.30,
      total_depreciable_basis: 45_000_000,
      estimated_year_1_paper_loss_per_100k: 30_000,
      note: 'New construction (2025) qualifies for bonus depreciation',
    },
  },
  waterfall_terms: {
    pref_rate: 0.08,
    pref_type: 'cumulative',
    pref_basis: 'committed_capital',
    hurdle_1_irr: 0.15,
    split_below_hurdle: { lp: 0.80, gp: 0.20 },
    hurdle_1_rate: 0.15,
    split_above_hurdle_1: { lp: 0.60, gp: 0.40 },
    catch_up: false,
  },
  fees: {
    acquisition_fee_pct: 1.5,               // 1.5% of purchase price ($937,500)
    acquisition_fee_dollars: 937_500,
    asset_management_fee_pct: 2.0,          // 2.0% of gross revenue, ongoing
    asset_management_fee_basis: 'Gross Revenue',
    property_management_fee_pct: 3.0,      // 3.0% of gross revenue, Gray Residential
    property_management_fee_basis: 'Gross Revenue',
    construction_mgmt_fee_pct: 0,          // N/A — no renovation
    preferred_return_pct: 8.0,             // 8% cumulative non-compounding
    preferred_return_type: 'cumulative_non_compounding',
  },
  deal_fees: {
    acquisition_fee_pct: 0.015,
    acquisition_fee_dollars: 937_500,
    asset_mgmt_fee_pct: 0.02,
    asset_mgmt_fee_basis: 'Gross Revenue',
    property_mgmt_fee_pct: 0.03,
    property_mgmt_fee_basis: 'Gross Revenue',
    construction_mgmt_fee_pct: 0,
    construction_mgmt_note: 'N/A - no renovation',
    preferred_return_pct: 0.08,
    preferred_return_type: 'cumulative_non_compounding',
  },
  cost_seg_data: {
    year_1_accelerated_depreciation_pct: 0.60,
    total_depreciable_basis: 35_000_000,
    estimated_year_1_paper_loss_per_100k: 82_000,
  },
  deal_terms: {
    total_raise: 22_100_000,
    min_investment: 100_000,
    projected_hold_years: 7,
    purchase_price: 62_500_000,
    total_capitalization: 65_832_000,
    total_units: 219,
    loan_amount: 43_750_000,
    interest_rate: 0.0517,
    ltv: 0.70,
    dscr: 1.03,
    io_months: 48,
    entry_cap_rate: 0.0584,
    exit_cap_rate: 0.0550,
    lender: 'Greystone (Fannie Mae)',
    target_close: '2026-06-01',
    asset_class: 'Class A Multifamily',
    strategy: 'Core-Plus',
    market: 'Columbus, OH MSA',
    submarket: 'Westerville / New Albany',
    developer: 'Preferred Living',
    year_built: 2025,
  },
  unit_mix: [
    { type: '1BR/1BA', count: 88, avg_sf: 667, market_rent: 1507, rent_per_sf: 2.26 },
    { type: '2BR/2BA', count: 108, avg_sf: 1073, market_rent: 1933, rent_per_sf: 1.80 },
    { type: '3BR/2BA', count: 23, avg_sf: 1246, market_rent: 2254, rent_per_sf: 1.81 },
  ],
  property_overview_md: `Fairmont Apartments is a 219-unit Class A multifamily community in Westerville, Ohio — one of Columbus' premier and most supply-constrained suburbs. Built to institutional standards (2025 delivery), the property features one, two, and three-bedroom floor plans with premium Class A finishes and a 15-year property tax abatement.

The community features a resort-style swimming pool, state-of-the-art fitness center, coworking lounge, dog park with agility equipment, outdoor entertainment areas, and attached garage options. Unit interiors include quartz countertops, stainless appliances, luxury vinyl plank flooring, and in-unit washer/dryer.

Gray Capital's acquisition basis of approximately $285,000 per unit reflects the Class A quality of the asset while remaining compelling relative to estimated replacement cost of $350K+/unit and Westerville's strong rental demand fundamentals.`,
  amenities: [
    'Resort-Style Swimming Pool', 'State-of-the-Art Fitness Center', 'Coworking Lounge', 'Dog Park',
    'Pet Wash Station', 'In-Unit Washer/Dryer', 'Attached Garages', 'Surface Parking',
    'Outdoor Entertainment Areas', 'Package Lockers', 'On-Site Maintenance', 'Electric Vehicle Charging',
  ],
  property_facts: {
    year_built: 2025,
    acreage: 12,
    building_style: 'Garden-style with structured parking',
    parking: 'Attached garages + surface',
    stories: '3-4 story',
    avg_unit_sf: 940,
    current_occupancy: 0.93,
    tax_abatement_years: 15,
  },
  renovation: {
    note: 'Brand new construction (2025) — no renovation required. Rent upside driven by lease-up and organic market rent growth.',
    interior_scope: [
      'Quartz countertops (installed)',
      'Stainless steel appliances (installed)',
      'Luxury vinyl plank flooring (installed)',
      'In-unit washer/dryer connections (installed)',
      'Modern lighting fixtures (installed)',
      'Designer bathroom finishes (installed)',
    ],
    exterior_scope: [
      'Resort-style pool & deck (complete)',
      'State-of-the-art fitness center (complete)',
      'Coworking lounge (complete)',
      'Dog park & pet wash station (complete)',
      'Outdoor entertainment areas (complete)',
    ],
    interior_cost_per_unit: 0,
    total_interior_budget: 0,
    exterior_budget: 0,
    total_budget: 0,
    timeline_months: 0,
    units_per_month: 0,
    comparable_premium_range: [0, 0],
  },
  benchmark_rates: {
    savings: 0.045,
    treasury_10yr: 0.042,
    muni_bond: 0.035,
    sp500_avg: 0.10,
  },
  market_data: {
    msa_name: 'Columbus-Dublin-Westerville',
    msa_population: 2_140_000,
    median_household_income: 68_200,
    cost_of_living_index: 94,
    unemployment_rate: 3.2,
    yoy_rent_growth: 4.2,
    vacancy_rate: 4.0,
    map_image_url: 'https://placehold.co/1200x600/1a1a2e/3B82F6?text=MSA+%26+Submarket+Map',
    map_caption: 'Columbus MSA — Westerville / New Albany submarket.',
    metro_overview_md: `The Columbus, Ohio Metropolitan Statistical Area is home to approximately 2.15 million residents, making it the 14th largest metro in the United States. The region has added over 120,000 residents since 2010, driven by a diversified economy anchored in healthcare, logistics, technology, and advanced manufacturing.\n\nColumbus benefits from a young, educated workforce — median age 32 — and one of the highest college-graduate densities in the Midwest. The metro's cost of living sits approximately 6% below the national average, while median household income has grown 4.2% annually over the past five years, creating a widening affordability advantage that attracts both residents and employers.`,
    metro_snapshot: {
      msa_population: '2,150,000',
      population_growth_5yr: '+5.8%',
      median_household_income: '$62,400',
      cost_of_living_index: '92 (vs 100 national)',
      major_airport: 'John Glenn Columbus International (CMH)',
      fortune_500_hqs: '3 (Nationwide, L Brands, Big Lots) + Intel $20B campus nearby',
    },
    employment_narrative_md: `Columbus has one of the most diversified and growing employment bases in the Midwest. The Ohio State University — with 60,000+ students and 30,000+ employees — anchors the metro, while OhioHealth and Nationwide Children's Hospital drive healthcare growth. The tech sector has exploded with Amazon AWS, Google, and Intel (a $20B semiconductor campus under construction in New Albany, 4 miles from Fairmont) anchoring the market. Anduril Industries recently committed a major defense manufacturing hub to the Columbus area, adding significant long-term demand.`,
    top_employers: [
      { employer: 'The Ohio State University', employees: 30_000, sector: 'Education & Research' },
      { employer: 'OhioHealth', employees: 35_000, sector: 'Healthcare' },
      { employer: 'Nationwide Children\'s Hospital', employees: 16_000, sector: 'Healthcare' },
      { employer: 'JPMorgan Chase', employees: 18_000, sector: 'Finance' },
      { employer: 'Amazon (AWS & Logistics)', employees: 15_000, sector: 'Technology & Logistics' },
      { employer: 'Intel (New Albany campus)', employees: 3_000, sector: 'Technology' },
      { employer: 'Nationwide Insurance', employees: 14_000, sector: 'Finance' },
      { employer: 'Google', employees: 5_000, sector: 'Technology' },
    ],
    sector_breakdown: [
      { sector: 'Healthcare', pct: 22 },
      { sector: 'Logistics & Distribution', pct: 15 },
      { sector: 'Government & Education', pct: 14 },
      { sector: 'Manufacturing', pct: 12 },
      { sector: 'Technology', pct: 10 },
      { sector: 'Finance & Insurance', pct: 9 },
      { sector: 'Retail & Hospitality', pct: 8 },
      { sector: 'Other', pct: 10 },
    ],
    population_narrative_md: `Central Indiana has seen steady population growth, outpacing the national average over the past decade. Net domestic in-migration has been positive since 2018, with the metro attracting residents from higher-cost markets in the Northeast and West Coast. The 25-34 age cohort — the primary renter demographic — has grown 8.2% since 2015, supporting sustained multifamily demand.`,
    population_trend: [
      { year: 2015, population: 2_012_000 },
      { year: 2016, population: 2_035_000 },
      { year: 2017, population: 2_056_000 },
      { year: 2018, population: 2_074_000 },
      { year: 2019, population: 2_095_000 },
      { year: 2020, population: 2_111_000 },
      { year: 2021, population: 2_120_000 },
      { year: 2022, population: 2_132_000 },
      { year: 2023, population: 2_141_000 },
      { year: 2024, population: 2_150_000 },
    ],
    supply_demand_narrative_md: `Columbus has seen moderate new multifamily construction concentrated in downtown and high-growth corridors, but the Westerville submarket has seen structurally limited new supply due to land constraints and zoning restrictions. Annual Columbus MSA deliveries have averaged approximately 4,200 units over the past five years, while net absorption has averaged 4,800 units — keeping the market in a healthy supply-demand balance. Fairmont Apartments benefits from Westerville's premium demand without the supply pressure of downtown submarkets.`,
    supply_demand: [
      { year: '2019', deliveries: 4_100, absorption: 3_900 },
      { year: '2020', deliveries: 3_200, absorption: 2_800 },
      { year: '2021', deliveries: 3_600, absorption: 5_100 },
      { year: '2022', deliveries: 4_200, absorption: 4_500 },
      { year: '2023', deliveries: 4_800, absorption: 4_100 },
      { year: '2024', deliveries: 3_500, absorption: 4_400 },
      { year: '2025P', deliveries: 3_100, absorption: 3_800 },
    ],
    vacancy_trend: [
      { year: 2019, vacancy: 5.8 },
      { year: 2020, vacancy: 6.2 },
      { year: 2021, vacancy: 4.1 },
      { year: 2022, vacancy: 4.5 },
      { year: 2023, vacancy: 5.0 },
      { year: 2024, vacancy: 4.8 },
    ],
    rent_growth_history: [
      { year: 2019, submarket: 3.2, msa: 2.8, national: 2.5 },
      { year: 2020, submarket: 1.8, msa: 1.5, national: 0.8 },
      { year: 2021, submarket: 8.5, msa: 7.2, national: 11.0 },
      { year: 2022, submarket: 6.1, msa: 5.4, national: 5.8 },
      { year: 2023, submarket: 3.8, msa: 3.2, national: 2.2 },
      { year: 2024, submarket: 3.5, msa: 3.0, national: 2.0 },
    ],
    rent_comparables: [
      { name: 'The Meridian at Westfield', distance: '1.2 mi', units: 280, year_built: 2003, avg_rent: 1_385, avg_sf: 1_020, rent_per_sf: 1.36, occupancy: 95.2, renovated: true },
      { name: 'Lakeside Village', distance: '2.1 mi', units: 196, year_built: 1998, avg_rent: 1_075, avg_sf: 935, rent_per_sf: 1.15, occupancy: 93.8, renovated: false },
      { name: 'Brookside Crossing', distance: '0.8 mi', units: 344, year_built: 2005, avg_rent: 1_420, avg_sf: 1_060, rent_per_sf: 1.34, occupancy: 96.1, renovated: true },
      { name: 'Fairmont Apartments (Current)', distance: '—', units: 219, year_built: 2025, avg_rent: 1_750, avg_sf: 956, rent_per_sf: 1.83, occupancy: 93.0, renovated: false, highlight: 'current' },
      { name: 'Fairmont Apartments (Pro Forma)', distance: '—', units: 219, year_built: 2025, avg_rent: 1_900, avg_sf: 956, rent_per_sf: 1.99, occupancy: 95.0, renovated: false, highlight: 'proforma' },
    ],
    market_risks: [
      {
        risk: 'Employer Concentration',
        detail: 'While diversified, healthcare represents 22% of employment. A major hospital system downsizing could impact the submarket.',
        mitigation: 'The top 10 employers collectively represent less than 15% of total metro employment. No single employer accounts for more than 3%.',
      },
      {
        risk: 'Interest Rate Sensitivity',
        detail: 'Rising rates could compress cap rates and impact exit valuations.',
        mitigation: "Gray Capital's conservative underwriting models exit cap rates 50-75 bps above acquisition cap rate. The deal structure uses fixed-rate debt, eliminating floating rate exposure during the hold.",
      },
      {
        risk: 'New Supply in Adjacent Submarkets',
        detail: 'Several Class A developments are under construction within 5 miles.',
        mitigation: "Fairmont's 15-year tax abatement and Class A quality position it competitively against new supply. The property's institutional-grade amenities and Westerville's supply-constrained submarket provide durable competitive advantages.",
      },
      {
        risk: 'Renovation Execution Risk',
        detail: 'Unit renovation timelines could extend due to contractor availability or supply chain issues.',
        mitigation: 'Gray Residential manages renovations in-house with established vendor relationships. Conservative scenario models a 30-month timeline vs. the base case of 24 months.',
      },
    ],
    midwest_thesis: [
      { icon: 'DollarSign', headline: 'Lower Basis, Higher Yield', description: 'Midwest acquisitions at $130-160K/unit vs. $250-400K+ in Sun Belt and Coastal — generating stronger day-one cash flow.' },
      { icon: 'Shield', headline: 'Affordable Rents = Sticky Residents', description: 'Average rent-to-income ratios below 25% mean lower turnover and more resilient demand through economic cycles.' },
      { icon: 'Briefcase', headline: 'Diversified Employment', description: 'Healthcare, logistics, manufacturing, and growing tech sectors reduce single-employer risk.' },
      { icon: 'TrendingDown', headline: 'Limited New Supply', description: 'Construction starts per capita in Midwest metros are 40-60% below Sun Belt markets, protecting existing properties from oversupply.' },
      { icon: 'Users', headline: 'Less Institutional Competition', description: 'Fewer institutional buyers chasing Midwest deals means better pricing and less compressed cap rates.' },
      { icon: 'BarChart3', headline: 'Population Stability + Growth', description: "Midwest metros aren't shrinking — they're growing steadily in the corridors where jobs are concentrating." },
    ],
    data_sources: 'CoStar Group, U.S. Census Bureau, Bureau of Labor Statistics, Indiana Department of Workforce Development, Gray Capital proprietary research (Gray Reports), and public filings. Market data as of Q4 2025.',
  },
  business_plan_data: {
    thesis_statement: 'Acquire below replacement cost, renovate 312 units over 24 months, achieve 15%+ rent premiums, and drive NOI growth through Gray Residential\'s operational playbook.',
    strategy_metrics: [
      { label: 'Renovation Budget', value: '$5.46M' },
      { label: 'Target Rent Premium', value: '+15%' },
      { label: 'Timeline', value: '24 months' },
      { label: 'Projected NOI Lift', value: '+32%' },
    ],
    value_pillars: [
      { icon: 'Hammer', title: 'Interior Renovations', description: 'Unit-by-unit upgrades to kitchens, baths, and living spaces — driving $150-225/unit monthly rent premiums.' },
      { icon: 'Building', title: 'Exterior & Amenity Upgrades', description: 'Community-wide improvements to curb appeal, common areas, and amenities that elevate the resident experience.' },
      { icon: 'Settings', title: 'Operational Improvements', description: 'Revenue management, expense optimization, and resident retention strategies executed by Gray Residential.' },
    ],
    interior_scope: [
      { item: 'Kitchen Countertops', spec: 'Quartz countertops replacing laminate', icon: 'ChefHat' },
      { item: 'Cabinetry', spec: 'Painted shaker-style cabinet doors with new hardware', icon: 'LayoutGrid' },
      { item: 'Appliances', spec: 'Stainless steel appliance package (range, dishwasher, microwave)', icon: 'Refrigerator' },
      { item: 'Flooring', spec: 'Luxury vinyl plank throughout — replacing carpet and vinyl sheet', icon: 'Layers' },
      { item: 'Lighting', spec: 'Brushed nickel fixtures with LED throughout', icon: 'Lightbulb' },
      { item: 'Bathrooms', spec: 'New vanity, mirror, fixtures, and hardware', icon: 'Bath' },
      { item: 'Paint', spec: 'Fresh two-tone paint scheme with accent walls', icon: 'Paintbrush' },
      { item: 'Hardware & Finishes', spec: 'Modern lever handles, outlet covers, window blinds', icon: 'Wrench' },
    ],
    interior_cost_summary: [
      { label: 'Average interior renovation cost per unit', value: '$15,000' },
      { label: 'Total interior renovation budget', value: '$4,680,000' },
      { label: 'Units to renovate', value: '312' },
      { label: 'Expected rent premium per unit', value: '$150 — $225/mo' },
      { label: 'Simple payback period', value: '6 — 8 years' },
      { label: 'ROI on renovation spend (annualized)', value: '12 — 18%', highlight: true },
    ],
    exterior_scope: [
      { item: 'Monument Signage', detail: 'New branded entrance signage with LED lighting', budget: 45_000 },
      { item: 'Landscaping', detail: 'Refreshed landscaping package, new mulch beds, seasonal color program', budget: 120_000 },
      { item: 'Clubhouse Renovation', detail: 'Updated furniture, new flooring, fresh paint, modern lighting, coworking area', budget: 180_000 },
      { item: 'Pool Deck', detail: 'Resurfaced pool deck, new lounge furniture, shade structures', budget: 95_000 },
      { item: 'Fitness Center', detail: 'New commercial-grade equipment, rubber flooring, mirrors, sound system', budget: 110_000 },
      { item: 'Dog Park', detail: 'Fenced dog park with agility equipment and waste stations', budget: 35_000 },
      { item: 'Building Exteriors', detail: 'Power washing, paint touch-up, new building numbers, updated entry lighting', budget: 145_000 },
      { item: 'Parking & Paving', detail: 'Seal coating, re-striping, pothole repair', budget: 50_000 },
    ],
    exterior_total: 780_000,
    timeline: {
      total_months: 30,
      milestones: [
        { month: 0, label: 'Acquisition Close', type: 'milestone', detail: 'Property closes, Gray Residential takes over management' },
        { month: 1, label: 'Renovation Kickoff', type: 'milestone', detail: 'Model units completed, vendor contracts finalized' },
        { month: 1, end_month: 3, label: 'Exterior Phase 1', type: 'phase', detail: 'Signage, landscaping, building exteriors', category: 'exterior' },
        { month: 1, end_month: 24, label: 'Interior Renovations', type: 'phase', detail: '312 units at ~13 units/month', category: 'interior' },
        { month: 6, label: '25% Complete', type: 'checkpoint', detail: '~78 units renovated, first rent premiums validated' },
        { month: 4, end_month: 8, label: 'Amenity Upgrades', type: 'phase', detail: 'Clubhouse, pool, fitness center, dog park', category: 'exterior' },
        { month: 12, label: '50% Complete', type: 'checkpoint', detail: '~156 units renovated, occupancy targets holding' },
        { month: 18, label: '75% Complete', type: 'checkpoint', detail: '~234 units renovated, NOI trajectory tracking to plan' },
        { month: 24, label: 'Renovation Complete', type: 'milestone', detail: 'All 312 units and common areas fully renovated' },
        { month: 24, end_month: 30, label: 'Stabilization', type: 'phase', detail: 'Lease-up of final renovated units to stabilized occupancy', category: 'operations' },
      ],
    },
    rent_bridge: [
      { label: 'Current Avg Rent', value: 1138, type: 'base' },
      { label: 'Renovation Premium', value: 172, type: 'increase' },
      { label: 'Market Growth (Yr 1-2)', value: 68, type: 'increase' },
      { label: 'Revenue Mgmt Upside', value: 22, type: 'increase' },
      { label: 'Stabilized Avg Rent', value: 1400, type: 'total' },
    ],
    rent_bridge_narrative: "Gray Capital's base case projects an average stabilized rent of $1,400/unit — a 23% increase from the current $1,138/unit average. This is achieved through three complementary strategies: unit renovations (driving $150-225/month premiums validated by market comps), organic market rent growth (3% annually in a supply-constrained submarket), and Gray Residential's revenue management platform that optimizes pricing and minimizes concessions.",
    operational_pillars: [
      {
        icon: 'TrendingUp',
        title: 'Revenue Management',
        points: [
          'Dynamic rent pricing using real-time market data',
          'Strategic concession management — minimize loss-to-lease',
          'Optimized lease expiration staggering to avoid seasonal vacancy spikes',
          'Other income optimization: pet fees, parking, storage, utility billback',
        ],
        stat_label: 'Other income opportunity',
        stat_value: '$75 → $110/unit/mo',
      },
      {
        icon: 'Scissors',
        title: 'Expense Optimization',
        points: [
          'In-house maintenance team reduces vendor reliance and emergency repair costs',
          'Bulk purchasing for renovation materials and maintenance supplies',
          'Energy efficiency upgrades (LED lighting, smart thermostats in common areas)',
          'Insurance negotiation and claims management',
        ],
        stat_label: 'Expense ratio reduction target',
        stat_value: '200 bps over hold',
      },
      {
        icon: 'Heart',
        title: 'Resident Retention',
        points: [
          'Average turn cost: $3,500-5,000 per unit — reducing turnover by 10% saves $100K+ annually',
          'Proactive maintenance response (target: 24-hour resolution for non-emergency)',
          'Resident events and community programming',
          'Seamless online leasing, maintenance requests, and rent payment',
        ],
        stat_label: 'Portfolio retention rate',
        stat_value: '58% → 62% target',
      },
    ],
    noi_projections: [
      { year: 0, conservative: 2_650_000, base: 2_650_000, upside: 2_650_000 },
      { year: 1, conservative: 2_780_000, base: 2_850_000, upside: 2_920_000 },
      { year: 2, conservative: 3_050_000, base: 3_210_000, upside: 3_400_000 },
      { year: 3, conservative: 3_280_000, base: 3_520_000, upside: 3_810_000 },
      { year: 4, conservative: 3_420_000, base: 3_740_000, upside: 4_120_000 },
      { year: 5, conservative: 3_530_000, base: 3_910_000, upside: 4_380_000 },
    ],
    noi_narrative: 'Under the base case, NOI grows from $2.65M at acquisition to $3.91M at Year 5 — a 47% increase driven by renovation rent premiums, organic rent growth, and operational efficiencies. This NOI trajectory supports the projected exit valuation and LP returns detailed in the Financial Explorer.',
    scenario_assumptions: [
      { assumption: 'Annual Rent Growth', conservative: '3.0%', base: '4.0%', upside: '5.0%', strategic: '6.0%' },
      { assumption: 'Stabilized Occupancy', conservative: '92%', base: '93.5%', upside: '95%', strategic: '96%' },
      { assumption: 'Expense Growth', conservative: '3.5%', base: '3.0%', upside: '2.5%', strategic: '2.5%' },
      { assumption: 'Exit Cap Rate', conservative: '6.00%', base: '5.50%', upside: '5.25%', strategic: '5.00%' },
      { assumption: 'Hold Period', conservative: '7 years', base: '7 years', upside: '7 years', strategic: '7 years' },
      { assumption: 'Tax Abatement', conservative: 'Full 15yr', base: 'Full 15yr', upside: 'Full 15yr', strategic: 'Full 15yr' },
    ],
  },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// ============================================
// FIRM-LEVEL DATA (Team & Track Record Spoke)
// ============================================

const DEMO_TEAM_MEMBERS = [
  { id: 'tm-001', name: 'Spencer Gray', title: 'Co-Founder, CEO', subtitle: null, entity: 'Gray Capital', photo_url: null, email: null, bio: null, sort_order: 1, is_active: true, display_section: 'leadership' },
  { id: 'tm-002', name: 'Alex Gray', title: 'Co-Founder', subtitle: 'President, Gray Construction & Design', entity: 'Gray Capital', photo_url: null, email: null, bio: null, sort_order: 2, is_active: true, display_section: 'leadership' },
  { id: 'tm-003', name: 'Jay Reeder', title: 'Chief Investment Officer', subtitle: null, entity: 'Gray Capital', photo_url: null, email: null, bio: null, sort_order: 3, is_active: true, display_section: 'leadership' },
  { id: 'tm-004', name: 'Andrew Bosway', title: 'Chief Operating Officer', subtitle: null, entity: 'Gray Capital', photo_url: null, email: null, bio: null, sort_order: 4, is_active: true, display_section: 'leadership' },
  { id: 'tm-005', name: 'Katrina Greene', title: 'Director of Property Management', subtitle: null, entity: 'Gray Residential', photo_url: null, email: null, bio: null, sort_order: 5, is_active: true, display_section: 'leadership' },
  { id: 'tm-006', name: 'Joe Powell', title: 'Director of Facilities', subtitle: null, entity: 'Gray Residential', photo_url: null, email: null, bio: null, sort_order: 6, is_active: true, display_section: 'leadership' },
  { id: 'tm-007', name: 'Blake Pieroni', title: 'Head of Investor Relations', subtitle: null, entity: 'Gray Capital', photo_url: null, email: 'Blake@graycapitalllc.com', bio: null, sort_order: 7, is_active: true, display_section: 'leadership' },
  { id: 'tm-008', name: 'Matt Bastnagel', title: 'Director, Marketing & Communications', subtitle: null, entity: 'Gray Capital', photo_url: null, email: null, bio: null, sort_order: 8, is_active: true, display_section: 'leadership' },
  { id: 'tm-009', name: 'Blake Pieroni', title: 'Head of Investor Relations', subtitle: null, entity: 'Gray Capital', photo_url: null, email: 'Blake@graycapitalllc.com', bio: null, sort_order: 1, is_active: true, display_section: 'ir' },
  { id: 'tm-010', name: 'Griffin Haddad', title: 'Investment Associate', subtitle: null, entity: 'Gray Capital', photo_url: null, email: 'Griffin@graycapitalllc.com', bio: null, sort_order: 2, is_active: true, display_section: 'ir' },
];

const DEMO_TRACK_RECORD = {
  full_cycle: [
    { id: 'tr-001', project_name: 'Abbey Court', market: 'Evansville, IN', entry_date: '2017-08-01', exit_date: '2021-12-01', net_irr: 38, net_equity_multiple: 3.44, status: 'realized', sort_order: 1 },
    { id: 'tr-002', project_name: 'Lexington Green / Villa Capri', market: 'Speedway, IN', entry_date: '2016-09-01', exit_date: '2020-10-01', net_irr: 26, net_equity_multiple: 2.33, status: 'realized', sort_order: 2 },
    { id: 'tr-003', project_name: 'Fountain Parc', market: 'Indianapolis, IN', entry_date: '2018-01-01', exit_date: '2021-09-01', net_irr: 31, net_equity_multiple: 2.39, status: 'realized', sort_order: 3 },
    { id: 'tr-004', project_name: 'Walnut Manor', market: 'Muncie, IN', entry_date: '2017-02-01', exit_date: '2020-09-01', net_irr: 23, net_equity_multiple: 1.70, status: 'realized', sort_order: 4 },
    { id: 'tr-005', project_name: 'Carmel Woods', market: 'Carmel, IN', entry_date: '2018-12-01', exit_date: '2022-06-01', net_irr: 33, net_equity_multiple: 2.54, status: 'realized', sort_order: 5 },
    { id: 'tr-006', project_name: 'Fox Brooke', market: 'Muncie, IN', entry_date: '2018-02-01', exit_date: '2020-09-01', net_irr: 23, net_equity_multiple: 1.70, status: 'realized', sort_order: 6 },
    { id: 'tr-007', project_name: 'The Reserve', market: 'Evansville, IN', entry_date: '2019-07-01', exit_date: '2022-05-01', net_irr: 28, net_equity_multiple: 2.00, status: 'realized', sort_order: 7 },
    { id: 'tr-008', project_name: 'Pinnacle on Meridian', market: 'Indianapolis, IN', entry_date: '2020-11-01', exit_date: '2022-10-01', net_irr: 38, net_equity_multiple: 1.90, status: 'realized', sort_order: 8 },
    { id: 'tr-009', project_name: 'Pebble Brook', market: 'Noblesville, IN', entry_date: '2020-11-01', exit_date: '2023-02-01', net_irr: 31, net_equity_multiple: 1.90, status: 'realized', sort_order: 9 },
    { id: 'tr-010', project_name: 'Autumn Trails', market: 'Indianapolis, IN', entry_date: '2020-09-01', exit_date: '2024-08-01', net_irr: 22, net_equity_multiple: 1.75, status: 'realized', sort_order: 10 },
  ],
  active_projects: [
    { id: 'tr-101', project_name: 'Oakdale Square', market: 'Bloomington, IN', acquired: '2017-01-01', cash_on_cash: 12, strategy: 'Value-Add', is_fund_asset: false, sort_order: 1 },
    { id: 'tr-102', project_name: 'Mad River', market: 'Dayton, OH', acquired: '2017-11-01', cash_on_cash: 9, strategy: 'Value-Add', is_fund_asset: false, sort_order: 2 },
    { id: 'tr-103', project_name: 'Gateway Crossing', market: 'McCordsville, IN', acquired: '2018-07-01', cash_on_cash: 13, strategy: 'Core Plus', is_fund_asset: false, sort_order: 3 },
    { id: 'tr-104', project_name: 'Nantucket Cove', market: 'Champaign, IL', acquired: '2018-12-01', cash_on_cash: 7.5, strategy: 'Core Plus', is_fund_asset: false, sort_order: 4 },
    { id: 'tr-105', project_name: 'Greenfield Crossing', market: 'Greenfield, IN', acquired: '2019-12-01', cash_on_cash: 7.5, strategy: 'Value-Add', is_fund_asset: false, sort_order: 5 },
    { id: 'tr-106', project_name: 'Aberdeen', market: 'Camby, IN', acquired: '2020-11-01', cash_on_cash: 7.5, strategy: 'Core Plus', is_fund_asset: false, sort_order: 6 },
    { id: 'tr-107', project_name: 'Villas on Fir', market: 'Granger, IN', acquired: '2020-12-01', cash_on_cash: 15, strategy: 'Core Plus', is_fund_asset: false, sort_order: 7 },
    { id: 'tr-108', project_name: 'Waterstone', market: 'Evansville, IN', acquired: '2021-02-01', cash_on_cash: 7.5, strategy: 'Value-Add', is_fund_asset: false, sort_order: 8 },
    { id: 'tr-109', project_name: 'Suncrest', market: 'Indianapolis, IN', acquired: '2021-08-01', cash_on_cash: 8, strategy: 'Value-Add', is_fund_asset: false, sort_order: 9 },
    { id: 'tr-110', project_name: 'Forest Ridge', market: 'Bloomington, IN', acquired: '2021-12-01', cash_on_cash: 7, strategy: 'Value-Add', is_fund_asset: false, sort_order: 10 },
    { id: 'tr-111', project_name: 'Park 88', market: 'Des Moines, IA', acquired: '2022-03-01', cash_on_cash: 7.5, strategy: 'Value-Add', is_fund_asset: false, sort_order: 11 },
    { id: 'tr-112', project_name: 'Crosswinds', market: 'Indianapolis, IN', acquired: '2022-05-01', cash_on_cash: 4, strategy: 'Value-Add', is_fund_asset: true, sort_order: 12 },
    { id: 'tr-113', project_name: 'Club Meridian', market: 'Okemos, MI', acquired: '2022-06-01', cash_on_cash: 6, strategy: 'Value-Add', is_fund_asset: true, sort_order: 13 },
    { id: 'tr-114', project_name: 'Sycamore Terrace', market: 'Terre Haute, IN', acquired: '2022-12-01', cash_on_cash: 6, strategy: 'Value-Add', is_fund_asset: true, sort_order: 14 },
    { id: 'tr-115', project_name: 'Echo Park', market: 'Bloomington, IN', acquired: '2023-02-01', cash_on_cash: 5, strategy: 'Core Plus', is_fund_asset: true, sort_order: 15 },
    { id: 'tr-116', project_name: 'River Club', market: 'Evansville, IN', acquired: '2024-04-01', cash_on_cash: 6, strategy: 'Value-Add', is_fund_asset: false, sort_order: 16 },
    { id: 'tr-117', project_name: 'Solana at the Crossing', market: 'Indianapolis, IN', acquired: '2024-08-01', cash_on_cash: 6, strategy: 'Core Plus', is_fund_asset: false, sort_order: 17 },
  ],
  summary: {
    avg_net_irr: 29.3,
    avg_equity_multiple: 2.16,
    avg_coc: 8,
    avg_hold_years: 3.5,
    total_realized: 10,
    total_active: 17,
    zero_capital_losses: true,
  },
};

const DEMO_CASE_STUDIES = [
  {
    id: 'cs-001',
    project_name: 'Villas on Fir',
    strategy: 'Core-Plus',
    market: 'Granger, IN (South Bend / Mishawaka area)',
    units: 290,
    year_built: 2018,
    purchase_price: 61_250_000,
    cash_on_cash: 15,
    irr: '30%+ (Projected)',
    hold_period: '10 years',
    narrative: "An A-Class, Core+ asset located in the heart of an overlooked, growing, high-income, tertiary market in our home state. The acquisition of Villas on Fir highlights our ability to source attractive deals often overlooked in \"flyover\" markets unrecognized by larger and/or coastal investment firms. Acquired in 2020, at the onset of a global pandemic, this project exhibits our understanding of, and willingness to quantify and take appropriate risks during uncertain times and in markets that are often overlooked. The keystone to our success is our ability to implement operational efficiencies aimed to directly drive returns — producing an average CoC of 15%.",
    image_url: null,
    stats: { price_per_unit: 211_207 },
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'cs-002',
    project_name: 'Club Meridian',
    strategy: 'Value-Add',
    market: 'Okemos, MI (Lansing area)',
    units: 406,
    year_built: 1989,
    purchase_price: 70_500_000,
    cash_on_cash: 7,
    irr: null,
    hold_period: 'Ongoing',
    narrative: "Club Meridian is a 406-unit, B-class, value-add multifamily asset in Okemos, Michigan. Since acquisition, NOI has increased by 27.5%, driven by operational efficiencies and strategic upgrades to common areas, building entryways, and select unit interiors, including appliance and flooring enhancements. Purchased at $174,000 per unit, the property exemplifies Gray Capital's ability to generate value through both physical improvements and operational efficiencies, leading to increased cash flow distributions and asset appreciation.",
    image_url: null,
    stats: { noi_increase: '27.5%', price_per_unit: 174_000, acquired: '06/2022' },
    sort_order: 2,
    is_active: true,
  },
];

const DEMO_TESTIMONIALS = [
  {
    id: 'test-001',
    name: 'Robert McDonald',
    attribution: 'Gray Capital Investor',
    quote: 'Fantastic reporting! Another syndication I\'m an LP with provides a single email with a brief update. Your updates and reporting are top shelf.',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'test-002',
    name: 'Cathi Scalise',
    attribution: 'Gray Capital Investor',
    quote: 'I am very happy with my Gray Fund investment! Thoughtful strategy and solid returns. I appreciate the regular updates, on-time distributions, and the overall communication from the principals.',
    sort_order: 2,
    is_active: true,
  },
];

const DEMO_COMPANY_DATA = {
  overview_stats: [
    { label: 'Founded', value: '2015' },
    { label: 'Headquarters', value: 'Indianapolis, IN' },
    { label: 'Portfolio', value: '7,500+ Units' },
    { label: 'Transaction Volume', value: '$2 Billion+' },
    { label: 'Active Markets', value: 'IN, MI, OH, KY' },
    { label: 'Strategies', value: 'Core+, Value-Add, Opportunistic' },
    { label: 'Market Type', value: 'Growing Secondary & Tertiary' },
    { label: 'Target Hold', value: '5\u201310 Years' },
    { label: 'Minimum Investment', value: '$100,000' },
  ],
  vertical_integration: [
    {
      entity: 'Gray Capital',
      division: 'Capital Management',
      icon: 'Landmark',
      functions: ['Acquisitions', 'Capital Raising', 'Asset Management', 'Fund Management', 'Dispositions'],
    },
    {
      entity: 'Gray Residential',
      division: 'Property Management',
      icon: 'Home',
      functions: ['Leasing', 'Marketing', 'Maintenance', 'Collections'],
    },
    {
      entity: 'Gray Construction & Design',
      division: 'Construction & Design',
      icon: 'Hammer',
      functions: ['Project Management', 'Vendor Sourcing', 'Interior Design'],
    },
    {
      entity: 'The Gray Report',
      division: 'Multifamily Intelligence',
      icon: 'BarChart3',
      functions: ['Industry Research', 'Market Data Aggregation', 'Research Publication', 'Weekly Podcast & Newsletter'],
    },
  ],
  investment_strategies: [
    {
      strategy: 'Value-Add',
      risk: 'Low \u2013 Moderate',
      irr: '15%+',
      coc: '8%',
      description: 'Acquiring a cash-flowing, usually older asset that may require renovations, upgrades, or operational changes that present a greater opportunity for upside.',
    },
    {
      strategy: 'Core Plus',
      risk: 'Low',
      irr: '13%+',
      coc: '7%',
      description: 'Acquiring stabilized, newer construction assets with high intrinsic value, requiring minimal to no physical improvement located in key or developing areas.',
    },
    {
      strategy: 'Build to Rent',
      risk: 'Low \u2013 Moderate',
      irr: '14%+',
      coc: '8%',
      description: 'A community rich in amenities, featuring single-family homes, townhomes, duplexes, and condos, all managed from a central onsite location.',
    },
    {
      strategy: 'Opportunistic',
      risk: 'Moderate \u2013 High',
      irr: '17%+',
      coc: '9%',
      description: 'Strategy involving more moving parts such as ground-up development, lease-up, or heavy asset repositioning. More risk but much greater potential for upside.',
    },
  ],
  deal_structure: {
    investment_terms: [
      { label: 'Minimum Investment', value: '$100,000' },
      { label: 'Distribution Cadence', value: 'Monthly' },
      { label: 'Preferred Return', value: '8%' },
      { label: 'LP/GP Split', value: '70/30' },
      { label: 'Avg. Sponsor Co-Invest', value: '14%' },
    ],
    one_time_fees: [
      { label: 'Acquisition', value: '1.75%' },
      { label: 'Loan Guarantee', value: '0.75%' },
    ],
    recurring_fees: [
      { label: 'Asset Management', value: '0.50%' },
      { label: 'Property Management', value: '3.0%' },
      { label: 'Construction Management', value: '5%' },
    ],
  },
  acquisition_criteria: {
    asset_characteristics: [
      { label: 'Asset Type', value: 'Market Rate Multifamily' },
      { label: 'Purchase Price', value: '$15M \u2013 $100M' },
      { label: 'Property Class', value: 'A & B' },
      { label: 'Vintage', value: '2000 or Newer' },
      { label: 'Unit Count', value: '200 \u2013 450' },
      { label: 'Geography', value: 'Midwest' },
    ],
    typical_financing: [
      { label: 'Interest Type', value: 'Fixed Rate' },
      { label: 'Financing', value: 'Long Term' },
      { label: 'Loan-to-Value', value: '50 \u2013 75%' },
    ],
    return_targets: [
      { label: 'IRR', value: '15 \u2013 25%' },
      { label: 'Equity Multiple', value: '2 \u2013 4x' },
      { label: 'Hold Period', value: '5 \u2013 10 Years' },
      { label: 'Avg Cash Flow', value: '6%+ CoC' },
    ],
  },
  differentiators: [
    {
      title: 'High GP Co-Invest (14% Average)',
      icon: 'Handshake',
      detail: 'High alignment of interest through 3x market GP co-investment. Gray Capital wins when investors win.',
    },
    {
      title: 'Industry-Leading Investor Reporting',
      icon: 'FileText',
      detail: 'Monthly, thorough updates on investment performance. Prompt, responsive, personal investor servicing.',
    },
    {
      title: 'In-House Research Division & Outlets',
      icon: 'BarChart3',
      detail: 'Internal research team fuels data-driven, goal-oriented corporate and property-level operations. Newsletter, research reports, podcasts, and YouTube content via The Gray Report.',
    },
  ],
  highlight_callouts: [
    { icon: 'Shield', headline: 'Capital Preservation is #1', detail: 'Never lost a single dollar of investor capital.' },
    { icon: 'Ban', headline: 'No Capital Calls, Ever', detail: 'Assets capitalized to mitigate risk \u2014 obsess over buying and financing the right way.' },
    { icon: 'TrendingUp', headline: 'Cash-Flow Focused', detail: 'Stable, steady cash flow at acquisition \u2014 operationally driven growth seeds upside.' },
  ],
  contact_info: {
    address: '1411 Roosevelt Avenue, Suite 106, Indianapolis, IN 46201',
    phone: '(317) 203-9457',
    website: 'GrayCapitalLLC.com',
    meetings_url: '#',
  },
  operations: {
    property_management: {
      title: 'Gray Residential',
      subtitle: 'Property Management',
      body: 'Our vertically integrated property management company manages 7,500+ units across our portfolio. Gray Residential handles leasing, marketing, maintenance, collections, and capital planning — keeping operations in-house for greater control and alignment with investor goals.',
      learn_more: 'Learn more about Gray Residential',
    },
    asset_management: {
      title: 'Asset Management Team',
      subtitle: 'Portfolio Oversight',
      body: 'Our asset management team oversees each property from acquisition through disposition. They work alongside Gray Residential and Gray Construction to execute business plans, track performance, and report to investors. Team members are assigned by property with clear accountability.',
    },
    construction: {
      title: 'Gray Construction and Design',
      subtitle: 'Construction Manager',
      body: 'In-house construction management and design ensure renovation scope, budgets, and timelines are executed efficiently. Gray Construction and Design handles project management, vendor sourcing, and interior design — reducing third-party coordination and cost.',
    },
    tech_stack: {
      title: 'Technology & Systems',
      subtitle: 'Tech Stack',
      items: [
        'Industry-leading property management software for accounting, leasing, and maintenance',
        'Online resident portals for rent payment and maintenance requests',
        'Real-time portfolio performance data and investor reporting',
        'Research and market data via The Gray Report',
      ],
    },
  },
};

module.exports = {
  DEMO_DEAL,
  DEMO_TEAM_MEMBERS,
  DEMO_TRACK_RECORD,
  DEMO_CASE_STUDIES,
  DEMO_TESTIMONIALS,
  DEMO_COMPANY_DATA,
};
