// Demo deal for development and demonstration
const DEMO_DEAL = {
  id: '00000000-0000-0000-0000-000000000001',
  slug: 'fairmont-apartments',
  name: 'Fairmont Apartments',
  status: 'live',
  property_address: '4985 Warner Rd, Westerville, OH 43081',
  city: 'Westerville',
  state: 'OH',
  total_units: 219,
  total_raise: 22_100_000,
  min_investment: 100_000,
  purchase_price: 62_500_000,
  projected_hold_years: 7,
  target_irr_base: 0.15,          // midpoint of 14-16% target
  target_irr_conservative: 0.10,
  target_equity_multiple: 2.2,
  target_coc: 0.084,              // avg cash-on-cash over hold
  hero_image_url: '/assets/deals/fairmont/hero.png',
  hero_video_url: '',
  video_url: '',
  market_analysis_md: `Columbus is the 14th largest MSA in the United States with a population of over 2.1 million and one of the fastest-growing metros in the Midwest. Columbus is the 14th largest city in the United States and 2nd largest in the Midwest. The metro is anchored by The Ohio State University (61,000+ students), major healthcare systems (OhioHealth, Nationwide Children's Hospital), technology (AWS, Google, Intel), and financial services (JPMorgan Chase, Nationwide Insurance). Metro GDP reached $182B in 2023.

The Westerville submarket, where Fairmont Apartments is located, benefits from top-rated schools, proximity to major employment corridors, and structurally limited new multifamily supply. Current submarket vacancy is approximately 4.0%, well below the national average.

Rent growth in the Columbus MSA has been strong and consistent. Intel's $28B semiconductor campus in New Albany (4 miles away) and Anduril's defense manufacturing hub represent significant long-term demand catalysts. New supply in Westerville is structurally constrained by land and zoning, creating a durable competitive moat for Fairmont Apartments.`,
  business_plan_md: `Fairmont Apartments is a brand new Class A multifamily community in Westerville, OH — one of Columbus' most supply-constrained and high-demand suburbs. The property benefits from a 15-year tax abatement that significantly reduces operating costs and enhances investor returns during the hold period.

Our strategy: acquire a high-quality, newly constructed asset at $285K/unit, below estimated replacement cost of $350K+, and capture organic rent growth in a supply-constrained submarket with major demand catalysts (Intel, Anduril, OSU). Gray Residential manages the property from day one, implementing our proven revenue management, retention, and operational efficiency systems.

The 15-year tax abatement is a significant differentiator — it substantially reduces property tax expense, boosting NOI and investor distributions. Combined with Class A quality and Westerville's structural supply constraints, Fairmont Apartments is positioned for consistent, low-execution-risk returns.`,
  team_override_md: null,
  fundraise_pct: null,
  sensitivity_data: {
    deal_slug: 'fairmont-apartments',
    scenarios: {
      downside: {
        label: 'Conservative',
        assumptions: {
          annual_rent_growth: 0.03,
          exit_cap: 0.0600,
          avg_occupancy: 0.92,
          annual_expense_growth: 0.035,
        },
        returns: {
          lp_irr: 0.105,          // ~10-11%
          equity_multiple: 1.8,
          avg_coc: 0.07,
          distribution_per_100k: 180_000,
        },
      },
      base: {
        label: 'Base Case',
        assumptions: {
          annual_rent_growth: 0.04,
          exit_cap: 0.0550,
          avg_occupancy: 0.935,
          annual_expense_growth: 0.03,
        },
        returns: {
          lp_irr: 0.15,           // 14-16% base case
          equity_multiple: 2.2,
          avg_coc: 0.084,
          distribution_per_100k: 220_000,
        },
      },
      upside: {
        label: 'Upside',
        assumptions: {
          annual_rent_growth: 0.05,
          exit_cap: 0.0525,
          avg_occupancy: 0.95,
          annual_expense_growth: 0.025,
        },
        returns: {
          lp_irr: 0.175,          // ~17-18%
          equity_multiple: 2.5,
          avg_coc: 0.095,
          distribution_per_100k: 250_000,
        },
      },
      strategic: {
        label: 'Strategic',
        description: 'Intel + Anduril demand catalysts fully realized',
        assumptions: {
          annual_rent_growth: 0.06,
          exit_cap: 0.0500,
          avg_occupancy: 0.96,
          annual_expense_growth: 0.025,
        },
        returns: {
          lp_irr: 0.21,           // 20%+
          equity_multiple: 2.8,
          avg_coc: 0.105,
          distribution_per_100k: 280_000,
        },
      },
    },
    sensitivity_tables: {
      rent_growth_vs_irr: [
        { rent_growth: 0.000, irr: 0.082, equity_multiple: 1.45, avg_coc: 0.051 },
        { rent_growth: 0.005, irr: 0.091, equity_multiple: 1.52, avg_coc: 0.055 },
        { rent_growth: 0.010, irr: 0.101, equity_multiple: 1.59, avg_coc: 0.058 },
        { rent_growth: 0.015, irr: 0.110, equity_multiple: 1.66, avg_coc: 0.062 },
        { rent_growth: 0.020, irr: 0.120, equity_multiple: 1.73, avg_coc: 0.065 },
        { rent_growth: 0.025, irr: 0.130, equity_multiple: 1.80, avg_coc: 0.068 },
        { rent_growth: 0.030, irr: 0.142, equity_multiple: 1.88, avg_coc: 0.070 },
        { rent_growth: 0.035, irr: 0.158, equity_multiple: 1.95, avg_coc: 0.072 },
        { rent_growth: 0.040, irr: 0.172, equity_multiple: 2.05, avg_coc: 0.075 },
        { rent_growth: 0.045, irr: 0.188, equity_multiple: 2.16, avg_coc: 0.078 },
        { rent_growth: 0.050, irr: 0.205, equity_multiple: 2.28, avg_coc: 0.081 },
      ],
      exit_cap_vs_irr: [
        { exit_cap: 0.040, irr: 0.225, equity_multiple: 2.50 },
        { exit_cap: 0.043, irr: 0.205, equity_multiple: 2.32 },
        { exit_cap: 0.045, irr: 0.192, equity_multiple: 2.20 },
        { exit_cap: 0.048, irr: 0.175, equity_multiple: 2.08 },
        { exit_cap: 0.050, irr: 0.165, equity_multiple: 2.00 },
        { exit_cap: 0.053, irr: 0.158, equity_multiple: 1.95 },
        { exit_cap: 0.055, irr: 0.145, equity_multiple: 1.85 },
        { exit_cap: 0.058, irr: 0.130, equity_multiple: 1.75 },
        { exit_cap: 0.060, irr: 0.118, equity_multiple: 1.68 },
        { exit_cap: 0.065, irr: 0.095, equity_multiple: 1.52 },
        { exit_cap: 0.070, irr: 0.072, equity_multiple: 1.38 },
      ],
      occupancy_vs_irr: [
        { occupancy: 0.85, irr: 0.065, equity_multiple: 1.32 },
        { occupancy: 0.87, irr: 0.082, equity_multiple: 1.42 },
        { occupancy: 0.89, irr: 0.100, equity_multiple: 1.55 },
        { occupancy: 0.91, irr: 0.120, equity_multiple: 1.68 },
        { occupancy: 0.93, irr: 0.142, equity_multiple: 1.82 },
        { occupancy: 0.94, irr: 0.158, equity_multiple: 1.95 },
        { occupancy: 0.95, irr: 0.168, equity_multiple: 2.02 },
        { occupancy: 0.96, irr: 0.180, equity_multiple: 2.12 },
        { occupancy: 0.97, irr: 0.195, equity_multiple: 2.22 },
        { occupancy: 0.98, irr: 0.210, equity_multiple: 2.32 },
      ],
      rent_growth_x_exit_cap: [
        { rent_growth: 0.020, exit_cap: 0.045, irr: 0.155 },
        { rent_growth: 0.020, exit_cap: 0.050, irr: 0.135 },
        { rent_growth: 0.020, exit_cap: 0.055, irr: 0.115 },
        { rent_growth: 0.020, exit_cap: 0.060, irr: 0.095 },
        { rent_growth: 0.035, exit_cap: 0.045, irr: 0.195 },
        { rent_growth: 0.035, exit_cap: 0.050, irr: 0.172 },
        { rent_growth: 0.035, exit_cap: 0.053, irr: 0.158 },
        { rent_growth: 0.035, exit_cap: 0.060, irr: 0.128 },
        { rent_growth: 0.045, exit_cap: 0.045, irr: 0.228 },
        { rent_growth: 0.045, exit_cap: 0.048, irr: 0.210 },
        { rent_growth: 0.045, exit_cap: 0.053, irr: 0.185 },
        { rent_growth: 0.045, exit_cap: 0.060, irr: 0.152 },
      ],
    },
    annual_cash_flows: {
      // 7-year projections (exact deck numbers)
      base: [
        { year: 1, egr: 5_100_000, noi: 3_000_000, tax_abatement: 895_000,  coc: 0.0753 },
        { year: 2, egr: 5_400_000, noi: 3_200_000, tax_abatement: 922_000,  coc: 0.0847 },
        { year: 3, egr: 5_600_000, noi: 3_300_000, tax_abatement: 950_000,  coc: 0.0800 },
        { year: 4, egr: 5_800_000, noi: 3_500_000, tax_abatement: 978_000,  coc: 0.0920 },
        { year: 5, egr: 6_000_000, noi: 3_600_000, tax_abatement: 1_000_000, coc: 0.0790 },
        { year: 6, egr: 6_200_000, noi: 3_800_000, tax_abatement: 1_000_000, coc: 0.0825 },
        { year: 7, egr: 6_500_000, noi: 4_000_000, tax_abatement: 1_100_000, coc: 0.0916 },
      ],
    },
    waterfall: {
      pref_rate: 0.08,
      pref_type: 'cumulative_non_compounding',
      pref_basis: 'committed_capital',
      lp_split: 0.80,
      gp_split: 0.20,
      hurdle_1_irr: 0.15,
      lp_split_above_hurdle_1: 0.60,
      gp_split_above_hurdle_1: 0.40,
      catch_up: false,
    },
    deal_terms: {
      total_raise: 22_100_000,
      min_investment: 100_000,
      projected_hold_years: 7,
      purchase_price: 62_500_000,
      total_capitalization: 65_832_000,
      total_units: 219,
      loan_amount: 43_750_000,
      interest_rate: 0.0517,
      ltv: 0.70,
      io_months: 48,
    },
    cost_seg: null, // Pending actual cost segregation study. Do not surface estimates to investors.
  },
  waterfall_terms: {
    pref_rate: 0.08,
    pref_type: 'cumulative',
    pref_basis: 'committed_capital',
    hurdle_1_irr: 0.15,
    split_below_hurdle: { lp: 0.80, gp: 0.20 },
    hurdle_1_rate: 0.15,
    split_above_hurdle_1: { lp: 0.60, gp: 0.40 },
    catch_up: false,
  },
  fees: {
    acquisition_fee_pct: 1.5,               // 1.5% of purchase price ($937,500)
    acquisition_fee_dollars: 937_500,
    asset_management_fee_pct: 1.5,          // 1.5% of gross revenue, ongoing
    asset_management_fee_basis: 'Gross Revenue',
    property_management_fee_pct: 3.0,      // 3.0% of gross revenue, Gray Residential
    property_management_fee_basis: 'Gross Revenue',
    construction_mgmt_fee_pct: 0,          // N/A — no renovation
    preferred_return_pct: 8.0,             // 8% cumulative non-compounding
    preferred_return_type: 'cumulative_non_compounding',
  },
  deal_fees: {
    acquisition_fee_pct: 0.015,
    acquisition_fee_dollars: 937_500,
    asset_mgmt_fee_pct: 0.015,
    asset_mgmt_fee_basis: 'Gross Revenue',
    property_mgmt_fee_pct: 0.03,
    property_mgmt_fee_basis: 'Gross Revenue',
    construction_mgmt_fee_pct: 0,
    construction_mgmt_note: 'N/A - no renovation',
    preferred_return_pct: 0.08,
    preferred_return_type: 'cumulative_non_compounding',
  },
  cost_seg_data: null, // Removed — no cost segregation study completed yet. Do not surface estimates to investors.
  deal_terms: {
    total_raise: 22_100_000,
    min_investment: 100_000,
    projected_hold_years: 7,
    purchase_price: 62_500_000,
    total_capitalization: 65_832_000,
    total_units: 219,
    loan_amount: 43_750_000,
    interest_rate: 0.0517,
    ltv: 0.70,
    dscr: 1.03,
    io_months: 48,
    entry_cap_rate: 0.0584,
    exit_cap_rate: 0.0550,
    lender: 'Greystone (Fannie Mae)',
    target_close: '2026-06-01',
    asset_class: 'Class A Multifamily',
    strategy: 'Core-Plus',
    market: 'Columbus, OH MSA',
    submarket: 'Westerville / New Albany',
    developer: 'Preferred Living',
    year_built: 2025,
  },
  unit_mix: [
    { type: '1BR/1BA', count: 88, avg_sf: 667, market_rent: 1507, rent_per_sf: 2.26 },
    { type: '2BR/2BA', count: 108, avg_sf: 1073, market_rent: 1933, rent_per_sf: 1.80 },
    { type: '3BR/2BA', count: 23, avg_sf: 1246, market_rent: 2254, rent_per_sf: 1.81 },
  ],
  property_overview_md: `Fairmont Apartments is a 219-unit Class A multifamily community in Westerville, Ohio — one of Columbus' premier and most supply-constrained suburbs. Built to institutional standards (2025 delivery), the property features one, two, and three-bedroom floor plans with premium Class A finishes and a 15-year property tax abatement.

The community features a resort-style swimming pool, state-of-the-art fitness center, coworking lounge, dog park with agility equipment, outdoor entertainment areas, and attached garage options. Unit interiors include quartz countertops, stainless appliances, luxury vinyl plank flooring, and in-unit washer/dryer.

Gray Capital's acquisition basis of approximately $285,000 per unit reflects the Class A quality of the asset while remaining compelling relative to estimated replacement cost of $350K+/unit and Westerville's strong rental demand fundamentals.`,
  amenities: [
    'Resort-Style Swimming Pool', 'State-of-the-Art Fitness Center', 'Coworking Lounge', 'Dog Park',
    'Pet Wash Station', 'In-Unit Washer/Dryer', 'Attached Garages', 'Surface Parking',
    'Outdoor Entertainment Areas', 'Package Lockers', 'On-Site Maintenance', 'Electric Vehicle Charging',
  ],
  property_facts: {
    year_built: 2025,
    acreage: 12,
    building_style: 'Garden-style with structured parking',
    parking: 'Attached garages + surface',
    stories: '3-4 story',
    avg_unit_sf: 940,
    current_occupancy: 0.93,
    tax_abatement_years: 15,
  },
  renovation: {
    note: 'Brand new construction (2025) — no renovation required. Rent upside driven by lease-up and organic market rent growth.',
    interior_scope: [
      'Quartz countertops (installed)',
      'Stainless steel appliances (installed)',
      'Luxury vinyl plank flooring (installed)',
      'In-unit washer/dryer connections (installed)',
      'Modern lighting fixtures (installed)',
      'Designer bathroom finishes (installed)',
    ],
    exterior_scope: [
      'Resort-style pool & deck (complete)',
      'State-of-the-art fitness center (complete)',
      'Coworking lounge (complete)',
      'Dog park & pet wash station (complete)',
      'Outdoor entertainment areas (complete)',
    ],
    interior_cost_per_unit: 0,
    total_interior_budget: 0,
    exterior_budget: 0,
    total_budget: 0,
    timeline_months: 0,
    units_per_month: 0,
    comparable_premium_range: [0, 0],
  },
  benchmark_rates: {
    savings: 0.045,
    treasury_10yr: 0.042,
    muni_bond: 0.035,
    sp500_avg: 0.10,
  },
  market_data: {
    msa_name: 'Columbus-Dublin-Westerville',
    msa_population: 2_140_000,
    median_household_income: 68_200,
    cost_of_living_index: 94,
    unemployment_rate: 3.2,
    yoy_rent_growth: 4.2,
    vacancy_rate: 4.0,
    metro_gdp_billions: 182,
    metro_gdp_source: 'Bureau of Economic Analysis, 2023',
    rent_to_income_pct: 17.5,
    rent_to_income_note: '3-mile median HHI ~$102K vs. $1,785 avg rent ($21,420/yr)',
    osu_enrollment: 60046,
    osu_enrollment_source: 'OSU Statistical Summary, Columbus campus, 2025',
    westerville_schools_enrollment: 14250,
    westerville_schools_rating: 'Excellent with Distinction (16 consecutive years)',
    westerville_schools_source: 'Westerville City Schools / SchoolMatch',
    franklin_county_census_growth: 'Grown every Census decade since 1900 (U.S. Census Bureau)',
    map_image_url: 'https://placehold.co/1200x600/1a1a2e/3B82F6?text=MSA+%26+Submarket+Map',
    map_caption: 'Columbus MSA — Westerville / New Albany submarket.',
    metro_overview_md: `The Columbus, Ohio Metropolitan Statistical Area is home to approximately 2.15 million residents, making it the 14th largest city in the United States (32nd largest MSA). The region has added over 120,000 residents since 2010, driven by a diversified economy anchored in healthcare, logistics, technology, and advanced manufacturing.\n\nColumbus benefits from a young, educated workforce — median age 32 — and one of the highest college-graduate densities in the Midwest. The metro's cost of living sits approximately 6% below the national average, while median household income has grown 4.2% annually over the past five years, creating a widening affordability advantage that attracts both residents and employers.`,
    metro_snapshot: {
      msa_population: '2,150,000',
      population_growth_5yr: '+5.8%',
      median_household_income: '$68,200',
      cost_of_living_index: '92 (vs 100 national)',
      major_airport: 'John Glenn Columbus International (CMH)',
      fortune_500_hqs: '5 (Cardinal Health, Nationwide, AEP, Huntington Bancshares, Vertiv) + Intel $28B campus nearby',
    },
    employment_narrative_md: `Columbus has one of the most diversified and growing employment bases in the Midwest. The Ohio State University — with 60,000+ students and 30,000+ employees — anchors the metro, while OhioHealth and Nationwide Children's Hospital drive healthcare growth. The tech sector has exploded with Amazon AWS, Google, and Intel (a $28B semiconductor campus under construction in New Albany, 4 miles from Fairmont) anchoring the market. Anduril Industries recently committed a major defense manufacturing hub to the Columbus area, adding significant long-term demand.`,
    top_employers: [
      { employer: 'The Ohio State University', employees: 30_000, sector: 'Education & Research' },
      { employer: 'OhioHealth', employees: 35_000, sector: 'Healthcare' },
      { employer: 'Nationwide Children\'s Hospital', employees: 16_000, sector: 'Healthcare' },
      { employer: 'JPMorgan Chase', employees: 18_000, sector: 'Finance' },
      { employer: 'Amazon (AWS & Logistics)', employees: 15_000, sector: 'Technology & Logistics' },
      { employer: 'Intel (New Albany campus)', employees: 3_000, sector: 'Technology' },
      { employer: 'Nationwide Insurance', employees: 14_000, sector: 'Finance' },
      { employer: 'Google', employees: 5_000, sector: 'Technology' },
    ],
    sector_breakdown: [
      { sector: 'Healthcare', pct: 22 },
      { sector: 'Logistics & Distribution', pct: 15 },
      { sector: 'Government & Education', pct: 14 },
      { sector: 'Manufacturing', pct: 12 },
      { sector: 'Technology', pct: 10 },
      { sector: 'Finance & Insurance', pct: 9 },
      { sector: 'Retail & Hospitality', pct: 8 },
      { sector: 'Other', pct: 10 },
    ],
    population_narrative_md: `Central Ohio has seen steady population growth, outpacing the national average over the past decade. Columbus is the 14th largest city in the United States and the 2nd largest in the Midwest after Chicago. Net domestic in-migration has been positive since 2018, with the metro attracting residents from higher-cost markets in the Northeast and West Coast. The 25-34 age cohort — the primary renter demographic — has grown 8.2% since 2015, supporting sustained multifamily demand. Franklin County has grown every Census decade since 1900 — a durability record unmatched in Ohio.`,
    population_trend: [
      { year: 2015, population: 2_012_000 },
      { year: 2016, population: 2_035_000 },
      { year: 2017, population: 2_056_000 },
      { year: 2018, population: 2_074_000 },
      { year: 2019, population: 2_095_000 },
      { year: 2020, population: 2_111_000 },
      { year: 2021, population: 2_120_000 },
      { year: 2022, population: 2_132_000 },
      { year: 2023, population: 2_141_000 },
      { year: 2024, population: 2_150_000 },
    ],
    supply_demand_narrative_md: `Columbus has seen moderate new multifamily construction concentrated in downtown and high-growth corridors, but the Westerville submarket has seen structurally limited new supply due to land constraints and zoning restrictions. Annual Columbus MSA deliveries have averaged approximately 4,200 units over the past five years, while net absorption has averaged 4,800 units — keeping the market in a healthy supply-demand balance. Fairmont Apartments benefits from Westerville's premium demand without the supply pressure of downtown submarkets.`,
    supply_demand: [
      { year: '2019', deliveries: 4_100, absorption: 3_900 },
      { year: '2020', deliveries: 3_200, absorption: 2_800 },
      { year: '2021', deliveries: 3_600, absorption: 5_100 },
      { year: '2022', deliveries: 4_200, absorption: 4_500 },
      { year: '2023', deliveries: 4_800, absorption: 4_100 },
      { year: '2024', deliveries: 3_500, absorption: 4_400 },
      { year: '2025', deliveries: 3_100, absorption: 3_800 },
      { year: '2026P', deliveries: 2_800, absorption: 3_500 },
    ],
    vacancy_trend: [
      { year: 2019, vacancy: 5.8 },
      { year: 2020, vacancy: 6.2 },
      { year: 2021, vacancy: 4.1 },
      { year: 2022, vacancy: 4.5 },
      { year: 2023, vacancy: 5.0 },
      { year: 2024, vacancy: 4.8 },
    ],
    rent_growth_history: [
      { year: 2019, submarket: 3.2, msa: 2.8, national: 2.5 },
      { year: 2020, submarket: 1.8, msa: 1.5, national: 0.8 },
      { year: 2021, submarket: 8.5, msa: 7.2, national: 11.0 },
      { year: 2022, submarket: 6.1, msa: 5.4, national: 5.8 },
      { year: 2023, submarket: 3.8, msa: 3.2, national: 2.2 },
      { year: 2024, submarket: 3.5, msa: 3.0, national: 2.0 },
      { year: 2025, submarket: 3.2, msa: 2.8, national: 2.3 },
    ],
        rent_comparables: [
      { name: 'Easton View', distance: '8.5 mi', units: 240, year_built: 2020, avg_rent: 1_620, avg_sf: 840, rent_per_sf: 1.58, occupancy: 94.0, renovated: false },
      { name: 'Flats on 5th', distance: '6.2 mi', units: 195, year_built: 2021, avg_rent: 1_650, avg_sf: 860, rent_per_sf: 1.65, occupancy: 93.5, renovated: false },
      { name: 'Polaris Towne Center', distance: '7.1 mi', units: 310, year_built: 2019, avg_rent: 1_640, avg_sf: 870, rent_per_sf: 1.74, occupancy: 95.0, renovated: false },
      { name: 'Dalton Residences', distance: '1.8 mi', units: 167, year_built: 2023, avg_rent: 1_680, avg_sf: 905, rent_per_sf: 1.83, occupancy: 92.0, renovated: false },
      { name: 'Reserve at Polaris', distance: '6.8 mi', units: 220, year_built: 2022, avg_rent: 1_700, avg_sf: 920, rent_per_sf: 1.81, occupancy: 93.0, renovated: false },
      { name: 'Fairmont Apartments', distance: '—', units: 219, year_built: 2025, avg_rent: 1_785, avg_sf: 928, rent_per_sf: 1.92, occupancy: 92.0, renovated: false, is_subject: true },
      { name: 'Camden New Albany', distance: '2.1 mi', units: 400, year_built: 2022, avg_rent: 1_720, avg_sf: 950, rent_per_sf: 1.71, occupancy: 91.0, renovated: false },
      { name: 'Arlo Apartments', distance: '5.4 mi', units: 285, year_built: 2023, avg_rent: 1_850, avg_sf: 980, rent_per_sf: 1.95, occupancy: 93.0, renovated: false },
      { name: 'Meridian at Easton', distance: '9.2 mi', units: 350, year_built: 2021, avg_rent: 1_920, avg_sf: 1_020, rent_per_sf: 2.05, occupancy: 94.0, renovated: false },
    ],
    // Loss-to-Lease by unit type (Slide 16 chart data)
    loss_to_lease: [
      { unit_type: '1BR-S', in_place: 1536, market: 1622, gap_pct: 5.3 },
      { unit_type: '1BR-L', in_place: 1466, market: 1516, gap_pct: 3.3 },
      { unit_type: '2BR', in_place: 1963, market: 2048, gap_pct: 4.2 },
      { unit_type: '3BR', in_place: 2282, market: 2561, gap_pct: 10.9 },
    ],
    // Lease-up pace (Slide 16 chart data)
    lease_up_pace: [
      { month: "Mar '25", units: 11 },
      { month: 'Apr', units: 3 },
      { month: 'May', units: 18 },
      { month: 'Jun', units: 33 },
      { month: 'Jul', units: 20 },
      { month: 'Aug', units: 31 },
      { month: 'Sep', units: 19 },
      { month: 'Oct', units: 25 },
      { month: 'Nov', units: 22 },
      { month: 'Dec', units: 10 },
    ],
    // Property vs Market occupancy (Slide 27 chart data)
    occupancy_tracking: [
      { quarter: "Q2 '22", fairmont: null, franklin_co: 96.8, columbus_msa: 94.3 },
      { quarter: "Q3 '22", fairmont: null, franklin_co: 95.5, columbus_msa: 94.0 },
      { quarter: "Q4 '22", fairmont: null, franklin_co: 92.9, columbus_msa: 91.8 },
      { quarter: "Q1 '23", fairmont: null, franklin_co: 89.3, columbus_msa: 90.7 },
      { quarter: "Q2 '23", fairmont: null, franklin_co: 84.6, columbus_msa: 90.2 },
      { quarter: "Q3 '23", fairmont: null, franklin_co: 81.4, columbus_msa: 90.7 },
      { quarter: "Q4 '23", fairmont: null, franklin_co: 83.5, columbus_msa: 90.0 },
      { quarter: "Q1 '24", fairmont: 58.3, franklin_co: 87.8, columbus_msa: 90.0 },
      { quarter: "Q2 '24", fairmont: 80.5, franklin_co: 90.6, columbus_msa: 90.3 },
      { quarter: "Q3 '24", fairmont: 88.7, franklin_co: 88.6, columbus_msa: 90.2 },
      { quarter: "Q4 '24", fairmont: 92.2, franklin_co: 86.0, columbus_msa: 90.5 },
      { quarter: "Q1 '25", fairmont: 94.0, franklin_co: 88.0, columbus_msa: 90.8 },
      { quarter: "Q2 '25", fairmont: 96.0, franklin_co: 89.0, columbus_msa: 91.0 },
      { quarter: "Q3 '25", fairmont: 94.0, franklin_co: 89.0, columbus_msa: 90.5 },
      { quarter: "Q4 '25", fairmont: 93.0, franklin_co: 90.0, columbus_msa: 90.2 },
      { quarter: "Q1 '26", fairmont: 92.0, franklin_co: 90.0, columbus_msa: 90.5 },
    ],
    // Columbus vs Midwest population growth (Slide 22 chart data)
    midwest_population_comparison: [
      { city: 'Columbus', growth_pct: 1.38 },
      { city: 'Indianapolis', growth_pct: 1.24 },
      { city: 'Kansas City', growth_pct: 1.15 },
      { city: 'U.S. Avg', growth_pct: 1.00 },
      { city: 'Minneapolis', growth_pct: 0.95 },
      { city: 'Cincinnati', growth_pct: 0.88 },
      { city: 'Chicago', growth_pct: 0.83 },
      { city: 'Detroit', growth_pct: 0.65 },
      { city: 'Cleveland', growth_pct: 0.26 },
      { city: 'St. Louis', growth_pct: 0.25 },
    ],
    // Rent by bedroom type vs comps (Slides 30-32 chart data)
    rent_by_bedroom: {
      one_br: [
        { name: 'Polaris Towne Center', rent: 1230 },
        { name: 'Easton View', rent: 1290 },
        { name: 'Flats on 5th', rent: 1320 },
        { name: 'Camden New Albany', rent: 1390 },
        { name: 'Dalton Residences', rent: 1410 },
        { name: 'Reserve at Polaris', rent: 1440 },
        { name: 'Fairmont', rent: 1507, is_subject: true },
        { name: 'Arlo Apartments', rent: 1540 },
        { name: 'Meridian at Easton', rent: 1580 },
      ],
      two_br: [
        { name: 'Polaris Towne Center', rent: 1480 },
        { name: 'Easton View', rent: 1530 },
        { name: 'Camden New Albany', rent: 1620 },
        { name: 'Flats on 5th', rent: 1660 },
        { name: 'Dalton Residences', rent: 1710 },
        { name: 'Reserve at Polaris', rent: 1740 },
        { name: 'Fairmont', rent: 1933, is_subject: true },
        { name: 'Arlo Apartments', rent: 1980 },
        { name: 'Meridian at Easton', rent: 2050 },
      ],
      three_br: [
        { name: 'Camden New Albany', rent: 1950 },
        { name: 'Polaris Towne Center', rent: 1990 },
        { name: 'Dalton Residences', rent: 2060 },
        { name: 'Flats on 5th', rent: 2090 },
        { name: 'Fairmont', rent: 2254, is_subject: true },
        { name: 'Reserve at Polaris', rent: 2310 },
        { name: 'Arlo Apartments', rent: 2380 },
        { name: 'Meridian at Easton', rent: 2450 },
      ],
    },
    // Cash-on-Cash progression (Slide 17 chart data)
    coc_progression: [
      { year: 'Yr 1', coc: 7.53, io: true },
      { year: 'Yr 2', coc: 8.47, io: true },
      { year: 'Yr 3', coc: 8.00, io: true },
      { year: 'Yr 4', coc: 9.20, io: true },
      { year: 'Yr 5', coc: 7.90, io: false },
      { year: 'Yr 6', coc: 8.25, io: false },
      { year: 'Yr 7', coc: 9.16, io: false },
    ],
    market_risks: [
      {
        risk: 'Employer Concentration',
        detail: 'While diversified, healthcare represents 22% of employment. A major hospital system downsizing could impact the submarket.',
        mitigation: 'The top 10 employers collectively represent less than 15% of total metro employment. No single employer accounts for more than 3%.',
      },
      {
        risk: 'Interest Rate Sensitivity',
        detail: 'Rising rates could cause cap rates to expand, reducing exit valuations.',
        mitigation: "Gray Capital's conservative underwriting models exit cap rates 50-75 bps above acquisition cap rate. The deal structure uses fixed-rate debt, eliminating floating rate exposure during the hold.",
      },
      {
        risk: 'New Supply in Adjacent Submarkets',
        detail: 'Several Class A developments are under construction within 5 miles.',
        mitigation: "Fairmont's 15-year tax abatement and Class A quality position it competitively against new supply. The property's institutional-grade amenities and Westerville's supply-constrained submarket provide durable competitive advantages.",
      },
      {
        risk: 'Lease-Up Execution Risk',
        detail: 'Concession burn-off could take longer than projected if Columbus supply remains elevated or macro conditions weaken.',
        mitigation: 'No renovation execution risk — Fairmont is brand-new 2025 construction with zero capex required. Concession burn-off modeled conservatively over 3-4 years. Deal works at 3% rent growth with 12.5%+ LP IRR.',
      },
    ],
    midwest_thesis: [
      { icon: 'DollarSign', headline: 'Lower Basis, Higher Yield', description: 'Midwest acquisitions at $130-160K/unit vs. $250-400K+ in Sun Belt and Coastal — generating stronger day-one cash flow.' },
      { icon: 'Shield', headline: 'Affordable Rents = Sticky Residents', description: 'Average rent-to-income ratios below 25% mean lower turnover and more resilient demand through economic cycles.' },
      { icon: 'Briefcase', headline: 'Diversified Employment', description: 'Healthcare, logistics, manufacturing, and growing tech sectors reduce single-employer risk.' },
      { icon: 'TrendingDown', headline: 'Limited New Supply', description: 'Construction starts per capita in Midwest metros are 40-60% below Sun Belt markets, protecting existing properties from oversupply.' },
      { icon: 'Users', headline: 'Less Institutional Competition', description: 'Fewer institutional buyers chasing Midwest deals means better pricing and less compressed cap rates.' },
      { icon: 'BarChart3', headline: 'Population Stability + Growth', description: "Midwest metros aren't shrinking — they're growing steadily in the corridors where jobs are concentrating." },
    ],
    data_sources: 'CoStar Group, U.S. Census Bureau, Bureau of Labor Statistics, Ohio Department of Job and Family Services, Gray Capital proprietary research (Gray Reports), and public filings. Market data as of Q4 2025.',
  },
  business_plan_data: {
    thesis_statement: 'Acquire brand-new Class A at $285K/door (15-20% below replacement cost), capture $290K of embedded loss-to-lease through natural lease rollover, and benefit from a 15-year tax abatement worth ~$895K+/year — with zero renovation risk.',
    strategy_metrics: [
      { label: 'Renovation Budget', value: '$0 (new construction)' },
      { label: 'Embedded LTL', value: '$290K/yr' },
      { label: 'Tax Abatement', value: '15-year, 100%' },
      { label: 'Projected NOI Lift', value: '+33% over hold' },
    ],
    value_pillars: [
      { icon: 'DollarSign', title: 'Loss-to-Lease Capture', description: '5.9% LTL embedded in the rent roll from lease-up mispricing. $290K/year captured on natural rollover — no renovation required.' },
      { icon: 'Shield', title: 'Tax Abatement', description: '15-year, 100% abatement on improved value through 2041. ~$895K+ annual savings. ~$12.2M NPV. Transfers to buyer at exit with ~8 years remaining.' },
      { icon: 'Settings', title: 'Operational Improvements', description: 'Revenue management, RUBS implementation, concession burn-off, and resident retention strategies executed by Gray Residential.' },
    ],
    interior_scope: [
      { item: 'Quartz Countertops', spec: 'Already installed — 2025 new construction', icon: 'ChefHat' },
      { item: 'Stainless Appliances', spec: 'Already installed — full package', icon: 'Refrigerator' },
      { item: 'LVP Flooring', spec: 'Already installed throughout', icon: 'Layers' },
      { item: 'In-Unit W/D', spec: 'Already installed — washer/dryer connections', icon: 'Settings' },
      { item: 'Modern Lighting', spec: 'Already installed — LED throughout', icon: 'Lightbulb' },
      { item: 'Designer Bathrooms', spec: 'Already installed — premium finishes', icon: 'Bath' },
    ],
    interior_cost_summary: [
      { label: 'Interior renovation required', value: '$0 — brand new' },
      { label: 'Exterior renovation required', value: '$0 — brand new' },
      { label: 'Total CapEx during hold', value: '$0' },
      { label: 'Amenity addition: 5 private yards', value: '$37,500 ($7,500 each)' },
      { label: 'Estimated rent increase per yard', value: '$100/mo' },
      { label: 'Medium-term / corporate lease potential', value: 'Upside opportunity', highlight: true },
    ],
    exterior_scope: [
      { item: '5 Private Yards', detail: 'Dedicated private yard spaces for select ground-floor units — premium amenity', budget: 37_500 },
      { item: 'Corporate / Medium-Term Leasing', detail: 'Furnished unit program targeting Anduril, Intel, defense contractors — premium rent opportunity', budget: 0 },
    ],
    exterior_total: 37_500,
    timeline: {
      total_months: 84,
      milestones: [
        { month: 0, label: 'Acquisition Close', type: 'milestone', detail: 'Property closes June 2026, Gray Residential takes over management' },
        { month: 1, end_month: 6, label: 'Concession Burn-Off Phase 1', type: 'phase', detail: '46% of leases roll by Aug 2026 — push to market on renewal', category: 'operations' },
        { month: 3, label: 'Private Yards Complete', type: 'milestone', detail: '5 private yards installed ($7,500 each), $100/mo premium' },
        { month: 3, label: 'Anduril Arsenal-1 Production Begins', type: 'milestone', detail: '4,008 jobs at $132K avg salary — demand catalyst' },
        { month: 6, end_month: 24, label: 'LTL Capture + RUBS Rollout', type: 'phase', detail: 'Natural lease rollover captures $290K LTL, RUBS adds $79-131K/yr', category: 'operations' },
        { month: 24, end_month: 48, label: 'Stabilization', type: 'phase', detail: 'Full concession burn-off, occupancy 93-95%, I/O period ends month 48', category: 'operations' },
        { month: 48, label: 'I/O Period Ends', type: 'milestone', detail: 'Amortization begins — debt service increases' },
        { month: 54, end_month: 66, label: 'Intel Ohio One Operational', type: 'phase', detail: '~3,000 engineers at $135K+ — exit cap compression catalyst', category: 'demand' },
        { month: 84, label: 'Projected Exit', type: 'milestone', detail: 'Sale at 5.50% exit cap, ~8 years abatement remaining for buyer' },
      ],
    },
    rent_bridge: [
      { label: 'Current Avg Rent', value: 1785, type: 'base' },
      { label: 'LTL Capture (rollover)', value: 110, type: 'increase' },
      { label: 'Market Growth (Yr 1-2)', value: 143, type: 'increase' },
      { label: 'Concession Burn-Off', value: 50, type: 'increase' },
      { label: 'Stabilized Avg Rent (Y3)', value: 2088, type: 'total' },
    ],
    rent_bridge_narrative: "Fairmont's current average rent of $1,785/unit reflects lease-up pricing during Columbus's peak supply cycle. Three complementary drivers lift rents without renovation: (1) $290K/year of loss-to-lease captured on natural rollover as early leases expire, (2) organic market rent growth of 4% annually in a supply-constrained submarket, and (3) concession burn-off as Westerville deliveries drop 75% in 2026. The 66 AMI-restricted units carry a built-in HUD escalator providing additional growth with near-zero concession exposure.",
    operational_pillars: [
      {
        icon: 'TrendingUp',
        title: 'Revenue Management',
        points: [
          'Dynamic rent pricing using real-time market data',
          'Strategic concession burn-off — 75% drop in Westerville deliveries supports pricing power',
          'Optimized lease expiration staggering to avoid seasonal vacancy spikes',
          'Other income optimization: RUBS, pet fees, parking, storage, private yards',
        ],
        stat_label: 'Other income opportunity',
        stat_value: '$259K → $450K+ Year 3',
      },
      {
        icon: 'Scissors',
        title: 'Expense Optimization',
        points: [
          'In-house maintenance team reduces vendor reliance and emergency repair costs',
          'Zero CapEx required — brand new 2025 construction',
          'Energy-efficient new construction (LED, modern HVAC, insulation)',
          'Insurance negotiation and claims management',
        ],
        stat_label: 'Expense ratio reduction target',
        stat_value: '150 bps over hold',
      },
      {
        icon: 'Heart',
        title: 'Resident Retention',
        points: [
          'Average turn cost: $3,500-5,000 per unit — reducing turnover by 10% saves $100K+ annually',
          'Proactive maintenance response (target: 24-hour resolution for non-emergency)',
          'Corporate housing outreach to Anduril, Intel, Victoria\'s Secret, Bath & Body Works',
          'Medium-term and furnished unit program for defense/tech contractor demand',
        ],
        stat_label: 'Portfolio retention rate',
        stat_value: '58% → 62% target',
      },
    ],
    noi_projections: [
      { year: 0, conservative: 2_971_000, base: 2_971_000, upside: 2_971_000 },
      { year: 1, conservative: 3_000_000, base: 3_000_000, upside: 3_100_000 },
      { year: 2, conservative: 3_100_000, base: 3_200_000, upside: 3_400_000 },
      { year: 3, conservative: 3_200_000, base: 3_300_000, upside: 3_600_000 },
      { year: 4, conservative: 3_300_000, base: 3_500_000, upside: 3_800_000 },
      { year: 5, conservative: 3_400_000, base: 3_600_000, upside: 4_000_000 },
    ],
    noi_narrative: 'Under the base case, NOI grows from $2.97M at acquisition to $3.6M at Year 5 — a 21% increase driven by loss-to-lease capture, concession burn-off, organic rent growth, and operational efficiencies. The 15-year tax abatement adds ~$895K+ annually on top, bringing effective NOI with abatement to $3.87M in Year 1 and growing through the hold period.',
    scenario_assumptions: [
      { assumption: 'Annual Rent Growth', conservative: '3.0%', base: '4.0%', upside: '5.0%', strategic: '6.0%' },
      { assumption: 'Stabilized Occupancy', conservative: '92%', base: '93.5%', upside: '95%', strategic: '96%' },
      { assumption: 'Expense Growth', conservative: '3.5%', base: '3.0%', upside: '2.5%', strategic: '2.5%' },
      { assumption: 'Exit Cap Rate', conservative: '6.00%', base: '5.50%', upside: '5.25%', strategic: '5.00%' },
      { assumption: 'Hold Period', conservative: '7 years', base: '7 years', upside: '7 years', strategic: '7 years' },
      { assumption: 'Tax Abatement', conservative: 'Full 15yr', base: 'Full 15yr', upside: 'Full 15yr', strategic: 'Full 15yr' },
      { assumption: 'Renovation Required', conservative: '$0', base: '$0', upside: '$0', strategic: '$0' },
    ],

    // ============================================
    // SUBMARKET DEMOGRAPHICS
    // Source: U.S. Census Bureau ACS 5-Year Estimates (2020–2024)
    // Methodology: Census tract centroids (TIGER/Web 2024) used to assign
    //   Franklin County, OH tracts to radii from 4985 Warner Rd, Westerville OH 43081.
    //   Values are population-weighted aggregates. White collar = Mgmt/Prof + Sales/Office.
    //   Note: Tract 007212 (New Albany enclave, avg HHI $306K) included at 3mi/5mi.
    // ESRI 2025 cross-check (investor deck): Avg HHI 3mi=$117,664, $100K+ HH=47%, White collar=77%
    // ============================================
    demographics: {
      radius_1mi: {
        total_population: 10278,
        total_households: 5400,
        pop_growth_5yr_pct: null,           // Tracts 007214 & 007215 not in 2019 ACS (newly split tracts)
        pop_growth_5yr_note: 'New tracts formed post-2019; 3mi proxy: +5.6%',
        median_age: 39.8,
        median_hh_income: 86370,
        avg_hh_income: 102152,
        per_capita_income: 53755,
        pct_hh_75k_plus: 56.0,
        pct_hh_100k_plus: 42.7,
        pct_bach_degree_plus: 54.1,
        pct_grad_prof_degree: 19.9,
        median_home_value: 324477,
        pct_owner_occupied: 55.6,
        pct_renter_occupied: 44.4,
        median_rent: 1551,
        unemployment_rate: 3.1,
        pct_white_collar: 76.9,
        tracts_included: 2,
      },
      radius_3mi: {
        total_population: 63648,
        total_households: 28736,
        pop_growth_5yr_pct: 5.6,             // Based on 6 of 12 tracts present in both 2019 and 2024 ACS
        pop_growth_5yr_note: 'Comparable-tract growth; 6 of 12 tracts not in 2019 ACS (newly created)',
        median_age: 37.6,
        median_hh_income: 101959,
        avg_hh_income: 123664,              // Investor deck (ESRI 2025) cites $117,664 — difference due to vintage
        per_capita_income: 56155,
        pct_hh_75k_plus: 60.9,
        pct_hh_100k_plus: 48.0,             // Investor deck (ESRI 2025) cites 47% — within rounding
        pct_bach_degree_plus: 54.9,
        pct_grad_prof_degree: 21.0,
        median_home_value: 349426,
        pct_owner_occupied: 53.6,
        pct_renter_occupied: 46.4,
        median_rent: 1607,
        unemployment_rate: 2.4,
        pct_white_collar: 75.7,             // Investor deck (ESRI 2025) cites 77% — within rounding
        tracts_included: 12,
      },
      radius_5mi: {
        total_population: 151561,
        total_households: 62181,
        pop_growth_5yr_pct: 4.4,             // Based on 19 of 30 tracts present in both 2019 and 2024 ACS
        pop_growth_5yr_note: 'Comparable-tract growth; 11 of 30 tracts not in 2019 ACS (newly created)',
        median_age: 36.7,
        median_hh_income: 107701,
        avg_hh_income: 130719,
        per_capita_income: 53978,
        pct_hh_75k_plus: 60.5,
        pct_hh_100k_plus: 47.3,
        pct_bach_degree_plus: 50.8,
        pct_grad_prof_degree: 19.8,
        median_home_value: 349167,
        pct_owner_occupied: 59.9,
        pct_renter_occupied: 40.1,
        median_rent: 1478,
        unemployment_rate: 2.8,
        pct_white_collar: 72.7,
        tracts_included: 30,
      },
      source: 'U.S. Census Bureau ACS 2020-2024 5-Year Estimates (Tables B01003, B01002, B19013, B19025, B19001, B19301, B15003, B25003, B25064, B25077, B23025, C24010). ESRI 2025 Estimates via Gray Capital Investor Deck (April 2026) for cross-reference.',
      generated: '2026-04-10',
    },
  },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

// ============================================
// FIRM-LEVEL DATA (Team & Track Record Spoke)
// ============================================

const DEMO_TEAM_MEMBERS = [
  { id: 'tm-001', name: 'Spencer Gray', title: 'Co-Founder, CEO', subtitle: null, entity: 'Gray Capital', photo_url: null, email: null, bio: null, sort_order: 1, is_active: true, display_section: 'leadership' },
  { id: 'tm-002', name: 'Alex Gray', title: 'Co-Founder', subtitle: 'President, Gray Construction & Design', entity: 'Gray Capital', photo_url: null, email: null, bio: null, sort_order: 2, is_active: true, display_section: 'leadership' },
  { id: 'tm-003', name: 'Jay Reeder', title: 'Chief Investment Officer', subtitle: null, entity: 'Gray Capital', photo_url: null, email: null, bio: null, sort_order: 3, is_active: true, display_section: 'leadership' },
  { id: 'tm-004', name: 'Andrew Bosway', title: 'Chief Operating Officer', subtitle: null, entity: 'Gray Capital', photo_url: null, email: null, bio: null, sort_order: 4, is_active: true, display_section: 'leadership' },
  { id: 'tm-005', name: 'Katrina Greene', title: 'Director of Property Management', subtitle: null, entity: 'Gray Residential', photo_url: null, email: null, bio: null, sort_order: 5, is_active: true, display_section: 'leadership' },
  { id: 'tm-006', name: 'Joe Powell', title: 'Director of Facilities', subtitle: null, entity: 'Gray Residential', photo_url: null, email: null, bio: null, sort_order: 6, is_active: true, display_section: 'leadership' },
  { id: 'tm-007', name: 'Blake Pieroni', title: 'Head of Investor Relations', subtitle: null, entity: 'Gray Capital', photo_url: null, email: 'Blake@graycapitalllc.com', bio: null, sort_order: 7, is_active: true, display_section: 'leadership' },
  { id: 'tm-008', name: 'Matt Bastnagel', title: 'Director, Marketing & Communications', subtitle: null, entity: 'Gray Capital', photo_url: null, email: null, bio: null, sort_order: 8, is_active: true, display_section: 'leadership' },

  { id: 'tm-010', name: 'Griffin Haddad', title: 'Investment Associate', subtitle: null, entity: 'Gray Capital', photo_url: null, email: 'Griffin@graycapitalllc.com', bio: null, sort_order: 2, is_active: true, display_section: 'ir' },
];

const DEMO_TRACK_RECORD = {
  full_cycle: [
    { id: 'tr-001', project_name: 'Abbey Court', market: 'Evansville, IN', entry_date: '2017-08-01', exit_date: '2021-12-01', net_irr: 38, net_equity_multiple: 3.44, status: 'realized', sort_order: 1 },
    { id: 'tr-002', project_name: 'Lexington Green / Villa Capri', market: 'Speedway, IN', entry_date: '2016-09-01', exit_date: '2020-10-01', net_irr: 26, net_equity_multiple: 2.33, status: 'realized', sort_order: 2 },
    { id: 'tr-003', project_name: 'Fountain Parc', market: 'Indianapolis, IN', entry_date: '2018-01-01', exit_date: '2021-09-01', net_irr: 31, net_equity_multiple: 2.39, status: 'realized', sort_order: 3 },
    { id: 'tr-004', project_name: 'Walnut Manor', market: 'Muncie, IN', entry_date: '2017-02-01', exit_date: '2020-09-01', net_irr: 23, net_equity_multiple: 1.70, status: 'realized', sort_order: 4 },
    { id: 'tr-005', project_name: 'Carmel Woods', market: 'Carmel, IN', entry_date: '2018-12-01', exit_date: '2022-06-01', net_irr: 33, net_equity_multiple: 2.54, status: 'realized', sort_order: 5 },
    { id: 'tr-006', project_name: 'Fox Brooke', market: 'Muncie, IN', entry_date: '2018-02-01', exit_date: '2020-09-01', net_irr: 23, net_equity_multiple: 1.70, status: 'realized', sort_order: 6 },
    { id: 'tr-007', project_name: 'The Reserve', market: 'Evansville, IN', entry_date: '2019-07-01', exit_date: '2022-05-01', net_irr: 28, net_equity_multiple: 2.00, status: 'realized', sort_order: 7 },
    { id: 'tr-008', project_name: 'Pinnacle on Meridian', market: 'Indianapolis, IN', entry_date: '2020-11-01', exit_date: '2022-10-01', net_irr: 38, net_equity_multiple: 1.90, status: 'realized', sort_order: 8 },
    { id: 'tr-009', project_name: 'Pebble Brook', market: 'Noblesville, IN', entry_date: '2020-11-01', exit_date: '2023-02-01', net_irr: 31, net_equity_multiple: 1.90, status: 'realized', sort_order: 9 },
    { id: 'tr-010', project_name: 'Autumn Trails', market: 'Indianapolis, IN', entry_date: '2020-09-01', exit_date: '2024-08-01', net_irr: 22, net_equity_multiple: 1.75, status: 'realized', sort_order: 10 },
  ],
  active_projects: [
    { id: 'tr-101', project_name: 'Oakdale Square', market: 'Bloomington, IN', acquired: '2017-01-01', cash_on_cash: 12, strategy: 'Value-Add', is_fund_asset: false, sort_order: 1 },
    { id: 'tr-102', project_name: 'Mad River', market: 'Dayton, OH', acquired: '2017-11-01', cash_on_cash: 9, strategy: 'Value-Add', is_fund_asset: false, sort_order: 2 },
    { id: 'tr-103', project_name: 'Gateway Crossing', market: 'McCordsville, IN', acquired: '2018-07-01', cash_on_cash: 13, strategy: 'Core Plus', is_fund_asset: false, sort_order: 3 },
    { id: 'tr-104', project_name: 'Nantucket Cove', market: 'Champaign, IL', acquired: '2018-12-01', cash_on_cash: 7.5, strategy: 'Core Plus', is_fund_asset: false, sort_order: 4 },
    { id: 'tr-105', project_name: 'Greenfield Crossing', market: 'Greenfield, IN', acquired: '2019-12-01', cash_on_cash: 7.5, strategy: 'Value-Add', is_fund_asset: false, sort_order: 5 },
    { id: 'tr-106', project_name: 'Aberdeen', market: 'Camby, IN', acquired: '2020-11-01', cash_on_cash: 7.5, strategy: 'Core Plus', is_fund_asset: false, sort_order: 6 },
    { id: 'tr-107', project_name: 'Villas on Fir', market: 'Granger, IN', acquired: '2020-12-01', cash_on_cash: 15, strategy: 'Core Plus', is_fund_asset: false, sort_order: 7 },
    { id: 'tr-108', project_name: 'Waterstone', market: 'Evansville, IN', acquired: '2021-02-01', cash_on_cash: 7.5, strategy: 'Value-Add', is_fund_asset: false, sort_order: 8 },
    { id: 'tr-109', project_name: 'Suncrest', market: 'Indianapolis, IN', acquired: '2021-08-01', cash_on_cash: 8, strategy: 'Value-Add', is_fund_asset: false, sort_order: 9 },
    { id: 'tr-110', project_name: 'Forest Ridge', market: 'Bloomington, IN', acquired: '2021-12-01', cash_on_cash: 7, strategy: 'Value-Add', is_fund_asset: false, sort_order: 10 },
    { id: 'tr-111', project_name: 'Park 88', market: 'Des Moines, IA', acquired: '2022-03-01', cash_on_cash: 7.5, strategy: 'Value-Add', is_fund_asset: false, sort_order: 11 },
    { id: 'tr-112', project_name: 'Crosswinds', market: 'Indianapolis, IN', acquired: '2022-05-01', cash_on_cash: 4, strategy: 'Value-Add', is_fund_asset: true, sort_order: 12 },
    { id: 'tr-113', project_name: 'Club Meridian', market: 'Okemos, MI', acquired: '2022-06-01', cash_on_cash: 6, strategy: 'Value-Add', is_fund_asset: true, sort_order: 13 },
    { id: 'tr-114', project_name: 'Sycamore Terrace', market: 'Terre Haute, IN', acquired: '2022-12-01', cash_on_cash: 6, strategy: 'Value-Add', is_fund_asset: true, sort_order: 14 },
    { id: 'tr-115', project_name: 'Echo Park', market: 'Bloomington, IN', acquired: '2023-02-01', cash_on_cash: 5, strategy: 'Core Plus', is_fund_asset: true, sort_order: 15 },
    { id: 'tr-116', project_name: 'River Club', market: 'Evansville, IN', acquired: '2024-04-01', cash_on_cash: 6, strategy: 'Value-Add', is_fund_asset: false, sort_order: 16 },
    { id: 'tr-117', project_name: 'Solana at the Crossing', market: 'Indianapolis, IN', acquired: '2024-08-01', cash_on_cash: 6, strategy: 'Core Plus', is_fund_asset: false, sort_order: 17 },
  ],
  summary: {
    avg_net_irr: 29.3,
    avg_equity_multiple: 2.16,
    avg_coc: 8,
    avg_hold_years: 3.5,
    total_realized: 10,
    total_active: 17,
    zero_capital_losses: true,
  },
};

const DEMO_CASE_STUDIES = [
  {
    id: 'cs-001',
    project_name: 'Villas on Fir',
    strategy: 'Core-Plus',
    market: 'Granger, IN (South Bend / Mishawaka area)',
    units: 290,
    year_built: 2018,
    purchase_price: 61_250_000,
    cash_on_cash: 15,
    irr: '30%+ (Projected)',
    hold_period: '10 years',
    narrative: "An A-Class, Core+ asset located in the heart of an overlooked, growing, high-income, tertiary market in our home state. The acquisition of Villas on Fir highlights our ability to source attractive deals often overlooked in \"flyover\" markets unrecognized by larger and/or coastal investment firms. Acquired in 2020, at the onset of a global pandemic, this project exhibits our understanding of, and willingness to quantify and take appropriate risks during uncertain times and in markets that are often overlooked. The keystone to our success is our ability to implement operational efficiencies aimed to directly drive returns — producing an average CoC of 15%.",
    image_url: null,
    stats: { price_per_unit: 211_207 },
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'cs-002',
    project_name: 'Club Meridian',
    strategy: 'Value-Add',
    market: 'Okemos, MI (Lansing area)',
    units: 406,
    year_built: 1989,
    purchase_price: 70_500_000,
    cash_on_cash: 7,
    irr: null,
    hold_period: 'Ongoing',
    narrative: "Club Meridian is a 406-unit, B-class, value-add multifamily asset in Okemos, Michigan. Since acquisition, NOI has increased by 27.5%, driven by operational efficiencies and strategic upgrades to common areas, building entryways, and select unit interiors, including appliance and flooring enhancements. Purchased at $174,000 per unit, the property exemplifies Gray Capital's ability to generate value through both physical improvements and operational efficiencies, leading to increased cash flow distributions and asset appreciation.",
    image_url: null,
    stats: { noi_increase: '27.5%', price_per_unit: 174_000, acquired: '06/2022' },
    sort_order: 2,
    is_active: true,
  },
];

const DEMO_TESTIMONIALS = [
  {
    id: 'test-001',
    name: 'Robert McDonald',
    attribution: 'Gray Capital Investor',
    quote: 'Fantastic reporting! Another syndication I\'m an LP with provides a single email with a brief update. Your updates and reporting are top shelf.',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'test-002',
    name: 'Cathi Scalise',
    attribution: 'Gray Capital Investor',
    quote: 'I am very happy with my Gray Fund investment! Thoughtful strategy and solid returns. I appreciate the regular updates, on-time distributions, and the overall communication from the principals.',
    sort_order: 2,
    is_active: true,
  },
];

const DEMO_COMPANY_DATA = {
  overview_stats: [
    { label: 'Founded', value: '2015' },
    { label: 'Headquarters', value: 'Indianapolis, IN' },
    { label: 'Portfolio', value: '7,500+ Units' },
    { label: 'Transaction Volume', value: '$2 Billion+' },
    { label: 'Active Markets', value: 'IN, MI, OH, KY' },
    { label: 'Strategies', value: 'Core+, Value-Add, Opportunistic' },
    { label: 'Market Type', value: 'Growing Secondary & Tertiary' },
    { label: 'Target Hold', value: '5\u201310 Years' },
    { label: 'Minimum Investment', value: '$100,000' },
  ],
  vertical_integration: [
    {
      entity: 'Gray Capital',
      division: 'Capital Management',
      icon: 'Landmark',
      functions: ['Acquisitions', 'Capital Raising', 'Asset Management', 'Fund Management', 'Dispositions'],
    },
    {
      entity: 'Gray Residential',
      division: 'Property Management',
      icon: 'Home',
      functions: ['Leasing', 'Marketing', 'Maintenance', 'Collections'],
    },
    {
      entity: 'Gray Construction & Design',
      division: 'Construction & Design',
      icon: 'Hammer',
      functions: ['Project Management', 'Vendor Sourcing', 'Interior Design'],
    },
    {
      entity: 'The Gray Report',
      division: 'Multifamily Intelligence',
      icon: 'BarChart3',
      functions: ['Industry Research', 'Market Data Aggregation', 'Research Publication', 'Weekly Podcast & Newsletter'],
    },
  ],
  investment_strategies: [
    {
      strategy: 'Value-Add',
      risk: 'Low \u2013 Moderate',
      irr: '15%+',
      coc: '8%',
      description: 'Acquiring a cash-flowing, usually older asset that may require renovations, upgrades, or operational changes that present a greater opportunity for upside.',
    },
    {
      strategy: 'Core Plus',
      risk: 'Low',
      irr: '13%+',
      coc: '7%',
      description: 'Acquiring stabilized, newer construction assets with high intrinsic value, requiring minimal to no physical improvement located in key or developing areas.',
    },
    {
      strategy: 'Build to Rent',
      risk: 'Low \u2013 Moderate',
      irr: '14%+',
      coc: '8%',
      description: 'A community rich in amenities, featuring single-family homes, townhomes, duplexes, and condos, all managed from a central onsite location.',
    },
    {
      strategy: 'Opportunistic',
      risk: 'Moderate \u2013 High',
      irr: '17%+',
      coc: '9%',
      description: 'Strategy involving more moving parts such as ground-up development, lease-up, or heavy asset repositioning. More risk but much greater potential for upside.',
    },
  ],
  deal_structure: {
    investment_terms: [
      { label: 'Minimum Investment', value: '$100,000' },
      { label: 'Distribution Cadence', value: 'Monthly' },
      { label: 'Preferred Return', value: '8%' },
      { label: 'LP/GP Split', value: '80/20 → 60/40 (above 15% IRR)' },
      { label: 'Avg. Sponsor Co-Invest', value: '14%' },
    ],
    one_time_fees: [
      { label: 'Acquisition', value: '1.5%' },
      { label: 'Loan Guarantee', value: '0.75%' },
    ],
    recurring_fees: [
      { label: 'Asset Management', value: '1.50%' },
      { label: 'Property Management', value: '3.0%' },
      { label: 'Construction Management', value: '5%' },
    ],
  },
  acquisition_criteria: {
    asset_characteristics: [
      { label: 'Asset Type', value: 'Market Rate Multifamily' },
      { label: 'Purchase Price', value: '$15M \u2013 $100M' },
      { label: 'Property Class', value: 'A & B' },
      { label: 'Vintage', value: '2000 or Newer' },
      { label: 'Unit Count', value: '200 \u2013 450' },
      { label: 'Geography', value: 'Midwest' },
    ],
    typical_financing: [
      { label: 'Interest Type', value: 'Fixed Rate' },
      { label: 'Financing', value: 'Long Term' },
      { label: 'Loan-to-Value', value: '50 \u2013 75%' },
    ],
    return_targets: [
      { label: 'IRR', value: '15 \u2013 25%' },
      { label: 'Equity Multiple', value: '2 \u2013 4x' },
      { label: 'Hold Period', value: '5 \u2013 10 Years' },
      { label: 'Avg Cash Flow', value: '6%+ CoC' },
    ],
  },
  differentiators: [
    {
      title: 'High GP Co-Invest (14% Average)',
      icon: 'Handshake',
      detail: 'High alignment of interest through 3x market GP co-investment. Gray Capital wins when investors win.',
    },
    {
      title: 'Industry-Leading Investor Reporting',
      icon: 'FileText',
      detail: 'Monthly, thorough updates on investment performance. Prompt, responsive, personal investor servicing.',
    },
    {
      title: 'In-House Research Division & Outlets',
      icon: 'BarChart3',
      detail: 'Internal research team fuels data-driven, goal-oriented corporate and property-level operations. Newsletter, research reports, podcasts, and YouTube content via The Gray Report.',
    },
  ],
  highlight_callouts: [
    { icon: 'Shield', headline: 'Capital Preservation is #1', detail: 'Never lost a single dollar of investor capital.' },
    { icon: 'Ban', headline: 'No Capital Calls, Ever', detail: 'Assets capitalized to mitigate risk \u2014 obsess over buying and financing the right way.' },
    { icon: 'TrendingUp', headline: 'Cash-Flow Focused', detail: 'Stable, steady cash flow at acquisition \u2014 operationally driven growth seeds upside.' },
  ],
  contact_info: {
    address: '1411 Roosevelt Avenue, Suite 106, Indianapolis, IN 46201',
    phone: '(317) 203-9457',
    website: 'GrayCapitalLLC.com',
    meetings_url: '#',
  },
  operations: {
    property_management: {
      title: 'Gray Residential',
      subtitle: 'Property Management',
      body: 'Our vertically integrated property management company manages 7,500+ units across our portfolio. Gray Residential handles leasing, marketing, maintenance, collections, and capital planning — keeping operations in-house for greater control and alignment with investor goals.',
      learn_more: 'Learn more about Gray Residential',
    },
    asset_management: {
      title: 'Asset Management Team',
      subtitle: 'Portfolio Oversight',
      body: 'Our asset management team oversees each property from acquisition through disposition. They work alongside Gray Residential and Gray Construction to execute business plans, track performance, and report to investors. Team members are assigned by property with clear accountability.',
    },
    construction: {
      title: 'Gray Construction and Design',
      subtitle: 'Construction Manager',
      body: 'In-house construction management and design ensure renovation scope, budgets, and timelines are executed efficiently. Gray Construction and Design handles project management, vendor sourcing, and interior design — reducing third-party coordination and cost.',
    },
    tech_stack: {
      title: 'Technology & Systems',
      subtitle: 'Tech Stack',
      items: [
        'Industry-leading property management software for accounting, leasing, and maintenance',
        'Online resident portals for rent payment and maintenance requests',
        'Real-time portfolio performance data and investor reporting',
        'Research and market data via The Gray Report',
      ],
    },
  },
};

module.exports = {
  DEMO_DEAL,
  DEMO_TEAM_MEMBERS,
  DEMO_TRACK_RECORD,
  DEMO_CASE_STUDIES,
  DEMO_TESTIMONIALS,
  DEMO_COMPANY_DATA,
};
